import type { GuideGoalId } from "@opensesame/guide-lang";
import { AUTHORITY_TUTORIALS } from "./authority-help.js";

/**
 * Every PWA capability names its walkthrough. Several share a ceremony,
 * so the map is many-to-one on purpose.
 */
export const CAPABILITY_TUTORIALS = {
  ...AUTHORITY_TUTORIALS,
  "vaults.switch": "vaults.switch",
  "vaults.travel": "vaults.travel",
  "vaults.travel_items": "vaults.travel",
  "vaults.duress_code": "vaults.duress-code",
  "vault.protectors.manage": "settings.security.review",
  "vault.protectors.rotate": "settings.security.review",
  "device.browser_reset": "vaults.switch",
  "host.health.pages": "host.health.check",
  "host.whoami": "identity.account.add",
  "receipts.read": "access.sessions.review",
  "identity.local.receipts.read": "access.sessions.review",
  "agent_identities.read": "access.sessions.review",
  "providers.list": "connection.create",
  "connections.list": "connection.create",
  "connections.inspect": "connection.create",
  "connections.create": "connection.create",
  "connections.credential.set": "connection.repair",
  "connections.remove": "connection.repair",
  "integrations.read": "connection.create",
  "certs.issue": "vault.item.create",
  "model_plane.read": "settings.model-provider",
  "model_plane.choose": "settings.model-provider",
  "backup.status": "settings.backup",
  "backup.target.set": "settings.backup",
  "vault.drive.sync": "settings.tailnet-sync",
  "vault.health.security_check": "feature.security-checks",
  "tailnet.devices.pair": "identity.tailnet.devices.manage",
  "tailnet.devices.read": "identity.tailnet.devices.manage",
  "tailnet.devices.manage": "identity.tailnet.devices.manage",
  "tailnet.keys.manage": "identity.tailnet.devices.manage",
  "tailnet.audit.read": "identity.tailnet.devices.manage",
  "plugins.surrogate_proxy.switch": "settings.surrogate-credentials",
  "plugins.surrogate_proxy.tripwires": "settings.surrogate-credentials",
  "plugins.browser_autofill.switch": "settings.browser-autofill",
  "plugins.pair": "settings.surrogate-credentials",
  "plugins.unpair": "settings.surrogate-credentials",
  "identity.notification.local.manage": "settings.local-notifications",
  "identity.notification.channels.read": "settings.notifications",
  "identity.notification.bindings.manage": "settings.notifications",
  "identity.notification.preferences.manage": "settings.notifications",
  "identity.login": "identity.sign-in",
  "identity.signout": "identity.sign-out",
  "vault.second_step.code": "vault.second-step.code",
  "vault.recovery_codes": "vault.recovery-codes",
  "identity.account_factors.list": "identity.account-factors",
  "identity.account_factors.enroll": "identity.account-factors",
  "identity.account_factors.remove": "identity.account-factors",
  "identity.switch_account": "identity.switch-account",
  "identity.whoami": "identity.account.add",
  "identity.admin": "identity.account.add",
  "identity.users.manage": "identity.users.manage",
  // Organization sign-in shares the directory's walkthrough: /identity is at
  // the support context's goal budget, and the panel is a target of its own.
  "identity.org_signin.upstream.manage": "identity.users.manage",
  "identity.org_signin.domains.manage": "identity.users.manage",
  "identity.org_signin.scim_tokens.manage": "identity.users.manage",
  "identity.org_signin.scim_token.mint": "identity.users.manage",
  "identity.local.directory.manage": "identity.local.directory.manage",
  "identity.local.access.manage": "identity.local.access.manage",
  "identity.local.policy.manage": "identity.local.policy.manage",
  "identity.local.requests.manage": "identity.local.requests.manage",
  "identity.local.passkeys.manage": "identity.local.passkeys.manage",
  "identity.local.organizations.read": "identity.local.organizations.member",
  "identity.local.organizations.membership.manage":
    "identity.local.organizations.member",
  "identity.local.agent.keys.manage": "identity.local.agent.keys.manage",
  "identity.local.application.authorize":
    "identity.local.application.authorize",
  "identity.local.siop.authorize": "identity.local.siop.authorize",
  "authority.portal.templates.manage": "authority.portal.templates.manage",
  "authority.portal.templates.read": "authority.portal.templates.read",
  "identity.agent.register": "identity.agents.manage",
  "identity.agent.manage": "identity.agents.manage",
  "identity.device.approve": "identity.device.approve",
  "identity.claim.accept": "identity.claim.accept",
  "identity.drop.open": "identity.drop.open",
  "identity.interaction.approve": "identity.interaction.approve",
  "identity.interaction.deny": "identity.interaction.approve",
  "identity.approval.activation": "identity.approval.review",
  "identity.approval.comparison": "identity.approval.review",
  "identity.approval.report": "identity.approval.review",
  "identity.approval.requests": "identity.approval.review",
  // The hand-off's browser fallback is the device approval (`/device`).
  "identity.authenticator.invoke": "identity.device.approve",
  "vault.workflow.find_references": "vault.item.create",
  "vault.workflow.inventory": "vault.item.create",
  "vault.workflow.audit_organization": "vault.health.review",
  "vault.workflow.env_template": "vault.item.edit",
  "vault.workflow.create_private": "vault.item.create",
  "vault.workflow.compare_private": "vault.item.edit",
  "vault.workflow.update_private": "vault.item.edit",
  "password_provider.read": "vault.item.edit",
  "password_provider.env_resolve": "vault.item.edit",
  "vault.items.search": "vault.item.create",
  "vault.items.read_meta": "vault.item.create",
  "vault.items.write_meta": "vault.item.create",
  "vault.items.reveal": "vault.item.create",
  "vault.totp.code": "vault.item.create",
  "vault.login_draft": "vault.item.create",
  "vault.item.create": "vault.item.create",
  "vault.item.set": "vault.item.create",
  "vault.item.share": "vault.item.create",
  "vault.account.pepper": "vault.item.create",
  "vault.item_types.list": "vault.item-types.install",
  "vault.item_types.install": "vault.item-types.install",
  "vault.item_types.marketplace": "vault.item-types.install",
  "vault.export": "vault.export",
  "vault.import": "vault.import",
  "vault.store_manifest.import": "vault.import",
  "app.status": "host.health.check",
  "app.navigate": "client.support",
  "client.support": "client.support",
  "client.tutorial": "client.support",
  "client.command_bar": "client.command-bar",
  "app.install": "app.install",
  "setup.first_run": "feature.identity",
  "delegations.claim": "identity.claim.accept",
  "shared_sessions.join_request": "feature.sharing",
  "shared_sessions.live_join": "feature.sharing",
  "shared_sessions.live_host": "feature.sharing",
  "browser.grant.renew": "feature.sharing",
  "connectors.directory.sync": "connection.create",
  "connectors.bind": "access.connectors",
  "connectors.connect.configure": "connection.create",
  "connectors.connect.authorize_user": "connection.create",
  "connectors.connect.token_check": "connection.create",
} satisfies Readonly<Record<string, GuideGoalId>>;
