import type { GuideGoalId } from "@opensesame/guide-lang";
import { AUTHORITY_TUTORIALS } from "./authority-help.js";

/**
 * Every PWA capability names its walkthrough. Several share a ceremony,
 * so the map is many-to-one on purpose.
 */
export const CAPABILITY_TUTORIALS = {
  ...AUTHORITY_TUTORIALS,
  "transport.status.view": "settings.transport",
  "transport.verify.run": "settings.transport",
  "transport.identity.reference": "settings.transport",
  "transport.capabilities.discover": "settings.transport",
  "vaults.switch": "vaults.switch",
  "vaults.travel": "vaults.switch",
  "host.health.pages": "host.health.check",
  "host.whoami": "identity.account.add",
  "receipts.read": "access.sessions.review",
  "agent_identities.read": "access.sessions.review",
  "providers.list": "connection.create",
  "connections.list": "connection.create",
  "connections.inspect": "connection.create",
  "connections.create": "connection.create",
  "connections.credential.set": "connection.repair",
  "connections.bindings": "connection.create",
  "connections.remove": "connection.repair",
  "integrations.read": "connection.create",
  "certs.issue": "vault.item.create",
  "configs.browse": "settings.secret-config",
  "configs.set": "settings.secret-config",
  "sync_targets.read": "settings.sync",
  "sync_targets.trigger": "settings.sync",
  "model_plane.read": "settings.model-provider",
  "model_plane.choose": "settings.model-provider",
  "changelog.read": "settings.changelog",
  "backup.status": "settings.backup",
  "backup.target.set": "settings.backup",
  "identity.login": "identity.sign-in",
  "identity.signout": "identity.sign-out",
  "vault.second_step.code": "vault.second-step.code",
  "vault.recovery_codes": "vault.recovery-codes",
  "identity.switch_account": "identity.switch-account",
  "identity.whoami": "identity.account.add",
  "identity.admin": "identity.account.add",
  "identity.users.manage": "identity.users.manage",
  "identity.local.directory.manage": "identity.local.directory.manage",
  "identity.local.access.manage": "identity.local.access.manage",
  "identity.local.policy.manage": "identity.local.policy.manage",
  "identity.local.requests.manage": "identity.local.requests.manage",
  "identity.local.passkeys.manage": "identity.local.passkeys.manage",
  "identity.local.agent.keys.manage": "identity.local.agent.keys.manage",
  "identity.local.application.authorize":
    "identity.local.application.authorize",
  "identity.local.siop.authorize": "identity.local.siop.authorize",
  "authority.portal.templates.manage": "authority.portal.templates.manage",
  "authority.portal.templates.read": "authority.portal.templates.read",
  "identity.agent.register": "identity.agents.manage",
  "identity.agent.manage": "identity.agents.manage",
  "identity.device.approve": "identity.device.approve",
  "identity.claim.accept": "identity.claim.accept",
  "identity.drop.open": "identity.drop.open",
  "identity.interaction.approve": "identity.interaction.approve",
  "identity.interaction.deny": "identity.interaction.approve",
  "identity.approval.activation": "identity.approval.review",
  "identity.approval.comparison": "identity.approval.review",
  "identity.approval.report": "identity.approval.review",
  "identity.approval.requests": "identity.approval.review",
  "vault.items.search": "vault.item.create",
  "vault.items.read_meta": "vault.item.create",
  "vault.items.write_meta": "vault.item.create",
  "vault.items.reveal": "vault.item.create",
  "vault.totp.code": "vault.item.create",
  "vault.login_draft": "vault.item.create",
  "vault.item_types.list": "vault.item-types.install",
  "vault.item_types.install": "vault.item-types.install",
  "vault.item_types.marketplace": "vault.item-types.install",
  "vault.export": "vault.export",
  "app.status": "host.health.check",
  "app.navigate": "client.support",
  "client.support": "client.support",
  "client.tutorial": "client.support",
  "client.command_bar": "client.command-bar",
  "app.install": "app.install",
  "setup.first_run": "setup.first-run",
  "delegations.claim": "setup.join-session",
  "shared_sessions.join_request": "setup.join-session",
  "browser.grant.renew": "setup.join-session",
  "connectors.directory.sync": "access.connectors",
  "connectors.bind": "access.connectors",
} satisfies Readonly<Record<string, GuideGoalId>>;
