/**
 * Goals and authored help the `connectors.external` capability contributes
 * (`tutorial-goal` and help-topic contributions, registered on activation).
 */

import type { GuideGoalDescriptor, HelpTopic } from "./goals.js";

export const CONNECTIONS_GOALS: readonly GuideGoalDescriptor[] = [
  {
    id: "connection.create",
    title: "Connect a provider",
    routes: [],
    guide: [
      "guide/1",
      'goal "connection.create"',
      'say "A provider connection is approved once. Every project and agent bound to it uses that authorization, and none of them ever holds the credential."',
      'navigate "/connections"',
      'wait route "/connections" timeout=15000',
      'focus "connections.provider-picker" "Find the provider here — a name, a category or a connector id all match." side=bottom',
      'wait target "connections.authorize" event=appear timeout=60000',
    ].join("\n"),
  },
  {
    id: "connection.repair",
    title: "Repair a broken connection",
    routes: [],
    guide: [
      "guide/1",
      'goal "connection.repair"',
      'say "A connection that is not usable yet is finished from the page that reports it. One the provider invalidated has to be authorized again."',
      'wait state "vault.unlocked" is=true timeout=60000',
      'navigate "/connections"',
      'wait route "/connections" timeout=15000',
      'focus "connections.connected" "Every connection shows its state on this panel. One that needs a person is also gathered at the top of the page, with a key to finish its authorization. Settings opens its page, where an OAuth connection offers Re-authorize." side=bottom',
      "end",
    ].join("\n"),
  },
  {
    id: "connection.review",
    title: "Find your way around Connections",
    routes: ["/connections"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "connection.review"',
      'say "Connections lists what this device is connected to and everything it could be. Nothing is connected until you approve it on that provider’s own page. This tour only points."',
      'wait state "vault.unlocked" is=true timeout=60000',
      'navigate "/connections"',
      'wait route "/connections" timeout=15000',
      'focus "connections.reload" "Reload reads the connection list again. Use it after finishing an authorization somewhere else." side=bottom',
      'focus "connections.provider-picker" "Add a connection, further down this page, is the provider catalog, grouped by category. Search it here with /; choosing a tile opens that provider’s own page." side=top',
      'wait target "connections.catalog" event=appear timeout=15000',
      'navigate "/connections/git"',
      'wait route "/connections/git" timeout=15000',
      'focus "connections.back" "Every provider page begins with this link back to the full list. Nothing changes here until you act on the page." side=right',
      'navigate "/connections"',
      'wait route "/connections" timeout=15000',
      'success "Connected holds what is already approved; the catalog is where a new connection starts."',
      "end",
    ].join("\n"),
  },
  {
    id: "connection.revoke",
    title: "Revoke a connection",
    routes: ["/connections"],
    libraryOnly: true,
    // Revoke is drawn only for a connection that exists.
    requires: ["connections.any"],
    guide: [
      "guide/1",
      'goal "connection.revoke"',
      'say "Revoking cuts a connection off for every project and agent bound to it. This tour only points; it never revokes anything."',
      'wait state "vault.unlocked" is=true timeout=60000',
      'navigate "/connections"',
      'wait route "/connections" timeout=15000',
      'focus "connections.connected" "Each row shows a connection’s state. Settings opens its page, where Revoke is." side=top',
      'wait target "connections.revoke" event=appear timeout=60000',
      'focus "connections.revoke" "Revoke asks twice. The first press arms it; the second revokes, and Keep it backs out. Bindings to it stop, and the provider is asked to invalidate the credential." side=top',
      'focus "connections.back" "Back returns to the full list." side=bottom',
      'navigate "/connections"',
      'wait route "/connections" timeout=15000',
      'focus "connections.attention" "A connection that exists but cannot be used yet is gathered here, with a key to finish its authorization. The panel is on the page only while one is waiting; with none, this step has nothing to light." side=bottom',
      'success "A revoked connection leaves the list. Connect it again from the catalog when you need it."',
      "end",
    ].join("\n"),
  },
  {
    id: "settings.backup",
    title: "Configure backup",
    routes: [],
    guide: [
      "guide/1",
      'goal "settings.backup"',
      'wait state "vault.unlocked" is=true timeout=60000',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.backups"',
      'focus "feature.backups" "The Backups section. It is built in, so it has no switch of its own." side=bottom',
      'focus "settings.backup" "Choose the git provider the vault backs up to under Backups, and switch it on." side=bottom',
      "end",
    ].join("\n"),
  },
  {
    id: "settings.tailnet-sync",
    title: "Sync the vault with your other devices",
    routes: [],
    guide: [
      "guide/1",
      'goal "settings.tailnet-sync"',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.networking"',
      'focus "feature.networking" "The Networking section. Its switch adds Tailnet sync, which keeps this vault in step with your other devices through a drive on your own tailnet. The drive only ever holds the sealed vault." side=bottom',
      'navigate "/settings/vaults"',
      'wait route "/settings/vaults" timeout=15000',
      'focus "settings.tailnet-sync" "Press the pair key to open the pairing sheet, then paste the code the drive printed, or open its link and the sheet opens with the code filled in. On a new device this sets the vault up here, and its master password opens it." side=top',
      "end",
    ].join("\n"),
  },
  {
    id: "settings.model-provider",
    title: "Choose voice and inference models",
    routes: [],
    // The picks are the on-device model's panel. WebMCP can leave the AI
    // section drawn while that model, and the remote support model, are off.
    requires: ["support.model-picks"],
    capabilities: ["support.local-ai"],
    guide: [
      "guide/1",
      'goal "settings.model-provider"',
      'wait state "vault.unlocked" is=true timeout=60000',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.ai"',
      'focus "feature.ai" "The AI section. Its switch adds the model choice beneath it." side=bottom',
      'focus "settings.model-provider" "Pick one provider/model slug for voice and one for inference. Hosted providers appear after Agent Harnesses connects them." side=bottom',
      "end",
    ].join("\n"),
  },
];

export const CONNECTIONS_HELP: readonly HelpTopic[] = [
  {
    id: "help.connection.create",
    title: "How do I connect a provider?",
    answer:
      "Connections → Add a connection. Search the catalog, open the provider's page, and approve it once on its Authorization panel. The credential is sealed with the connection; projects and agents are bound to the connection afterwards, and never receive the credential itself.",
    routes: [],
    goal: "connection.create",
    keywords: [
      "connection",
      "connect",
      "provider",
      "integration",
      "oauth",
      "authorize",
      "link",
      "catalog",
      "github",
      "google",
      "slack",
      "api",
    ],
  },
  {
    id: "help.connection.broken",
    title: "A connection stopped working. What now?",
    answer:
      "Open that connector's page from Connections. An authorization that only needs a fresh credential offers Renew now; one the provider has invalidated has to be authorized again. If the whole list fails to load, check connectivity on the statusline first.",
    routes: [],
    goal: "connection.repair",
    keywords: [
      "broken",
      "stopped working",
      "failed",
      "failing",
      "error",
      "renew",
      "expired",
      "revoked",
      "reauthorize",
      "fix",
      "repair",
      "not working",
    ],
  },
  {
    id: "help.tailnet-sync",
    title: "How do I sync the vault to my phone or another computer?",
    answer:
      "Run opensesame daemon drive create on a machine on your tailnet, switch Networking on in Settings → Capabilities, then paste its pairing code in Settings → Vaults on each device. Every device merges on its own side; the drive never holds a key.",
    routes: [],
    goal: "settings.tailnet-sync",
    keywords: [
      "sync",
      "tailscale",
      "tailnet",
      "phone",
      "another device",
      "enpass",
      "wi-fi sync",
      "pair",
    ],
  },
  {
    id: "help.backup",
    title: "How do I back up the vault?",
    answer:
      "Export, in the Vault's path strip, saves one encrypted backup file that the master password opens and Import restores. To keep a copy off this device, Settings → Capabilities → Backups: choose the git provider — GitHub, GitLab, Bitbucket, Codeberg or any git remote — the encrypted vault backs up to, and switch that provider on.",
    routes: [],
    goal: "settings.backup",
    keywords: [
      "backup",
      "back up",
      "export",
      "restore",
      "github",
      "sync",
      "copy",
      "another device",
      "recover",
      "move vault",
    ],
  },
];
