/**
 * One tutorial per feature: what it is, where its section lives in Settings ›
 * Capabilities, and what turning it on gives you.
 *
 * Every optional capability sits under a section of that one page, so a
 * feature tour is the same walk every time and cannot depend on the feature
 * being on: it navigates to the page, points at the section heading, and says
 * in a closing step what appears once the switch is. The sections that already
 * have a task-shaped tour — Backups, Networking, Local notifications, AI,
 * Browser autofill, Surrogate credentials — are not repeated here;
 * `FEATURE_TUTORIALS` below says which tutorial a feature opens.
 *
 * Authored, checked-in prose; compiled by the same parser and validator model
 * output goes through (ADR 0088).
 */

import type { GuideGoalDescriptor } from "./goals.js";

export const FEATURE_GOALS: readonly GuideGoalDescriptor[] = [
  {
    id: "feature.identity",
    title: "Turn on Identity",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.identity"',
      'say "Identity is how people and applications are known here. Switching it on adds browser-local identity (a directory of people, agents and devices on this device), self-issued OpenID, operator identity providers and ambient single sign-on."',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.identity"',
      'focus "feature.identity" "The Identity section. The switch on its right adds every identity capability this installation can run; the tiles under it switch each one on its own." side=bottom',
      'say "With Identity on, an Identity screen joins the section list. Signing in to an account never opens the vault: the vault\'s own keys do."',
      'success "That is Identity."',
      "end",
    ].join("\n"),
  },
  {
    id: "feature.access",
    title: "Turn on Access",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.access"',
      'say "Access is where you decide what an agent or an application may do for you: grants, requests waiting on a decision, running sessions, resources and policies."',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.access"',
      'focus "feature.access" "The Access section. Its switch adds the Access screen to this installation." side=bottom',
      'say "With Access on, an Access screen joins the section list, with tabs for grants, requests, sessions, resources and policies. A grant can be revoked from there."',
      'success "That is Access."',
      "end",
    ].join("\n"),
  },
  {
    id: "feature.connections",
    title: "Turn on Connections",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.connections"',
      'say "Connections link this vault to the services an agent or a person works with: the embedded catalogue, Vercel Connect sessions, the GitHub App, and a Nango-compatible directory read by reference. A connector arrives by reference, never by credential."',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.connections"',
      'focus "feature.connections" "The Connections section. Its switch adds the Connections screen." side=bottom',
      'say "With Connections on, a Connections screen joins the section list, and Access can bind each connector to the people and agents allowed to use it."',
      'success "That is Connections."',
      "end",
    ].join("\n"),
  },
  {
    id: "feature.directory",
    title: "Turn on Directory provisioning",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.directory"',
      "say \"Directory provisioning manages the people, agents and devices of an organization in the Identity API's directory, and the organization's own sign-in: its upstream issuer, its email domains and its provisioning tokens.\"",
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.directory"',
      'focus "feature.directory" "The Directory section. Its switch adds directory management to the Identity screen." side=bottom',
      'say "It works against an Identity API your operator configures, so it has something to manage only where one is set up."',
      'success "That is Directory."',
      "end",
    ].join("\n"),
  },
  {
    id: "feature.encryption",
    title: "Choose where keys can live",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.encryption"',
      'say "A vault is sealed by keys that open it. The Encryption section lists the key services this installation can reference — a cloud key service, a hardware key, an age recipient — and the browser\'s own WebCrypto, which needs nothing."',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.encryption"',
      'focus "feature.encryption" "The Encryption section has no switch: it is built in. Each tile opens that provider\'s page, where it is configured by reference." side=bottom',
      'say "A cloud key service holds a credential, and that credential is sealed in the vault, never kept in the clear. Nothing is sent to a provider until you connect it."',
      'success "That is Encryption."',
      "end",
    ].join("\n"),
  },
  {
    id: "feature.certificates",
    title: "Connect a certificate authority",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.certificates"',
      'say "Certificate authority lists the authorities this installation can connect to — Let\'s Encrypt, ZeroSSL and Cloudflare Origin CA."',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.certificates"',
      'focus "feature.certificates" "The Certificate authority section. Each tile opens that authority\'s page, where it is connected by reference." side=bottom',
      'say "Nothing is sent to an authority until you connect it. Certificates themselves are vault items, added from the vault."',
      'success "That is the certificate authority."',
      "end",
    ].join("\n"),
  },
  {
    id: "feature.password-managers",
    title: "Connect a password manager",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.password-managers"',
      'say "Password managers lists the ones this installation can connect to — 1Password, Bitwarden, Proton Pass, Passbolt and others — so the tools you already use keep working beside the vault."',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.password-managers"',
      'focus "feature.password-managers" "The Password managers section has no switch: it is built in. Each tile opens that manager\'s page." side=bottom',
      'say "A connection is by reference. Nothing from another manager is read until you connect it, and an agent never reads a value out of one."',
      'success "That is Password managers."',
      "end",
    ].join("\n"),
  },
  {
    id: "feature.cloud-secret-storage",
    title: "Connect a cloud secret store",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.cloud-secret-storage"',
      'say "Cloud secret storage lists the stores this installation can connect to — AWS, Azure, Google Cloud, Doppler, Vault, OpenBao and others."',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.cloud-secret-storage"',
      'focus "feature.cloud-secret-storage" "The Cloud secret storage section has no switch: it is built in. Each tile opens that store\'s page." side=bottom',
      'say "A connection is by reference, and the credential behind it is sealed in the vault. Nothing is sent to a store until you connect it."',
      'success "That is Cloud secret storage."',
      "end",
    ].join("\n"),
  },
  {
    id: "feature.local-storage",
    title: "Connect a local store",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.local-storage"',
      'say "Local storage lists the stores that live on this device or next to it — KeePass, the system keychain, a password-store directory and the sealed local store."',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.local-storage"',
      'focus "feature.local-storage" "The Local storage section has no switch: it is built in. Each tile opens that store\'s page." side=bottom',
      'say "A local store is read on this device. Nothing about it is sent to a provider."',
      'success "That is Local storage."',
      "end",
    ].join("\n"),
  },
  {
    id: "feature.encrypted-search",
    title: "Turn on Encrypted search",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.encrypted-search"',
      'say "Encrypted search keeps the databases this browser holds for identifiers - history backups and retired-password digests - encrypted in a way that can still be searched. With it on, no table, field, id or name is readable in the browser\'s storage."',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.encrypted-search"',
      'focus "feature.encrypted-search" "The Encrypted search section. Its switch moves those databases across and deletes the ones that had readable names." side=bottom',
      'say "Nothing is searchable until a lookup needs it. These databases belong to this browser: they are not synced, and Reset this browser removes them."',
      'success "That is Encrypted search."',
      "end",
    ].join("\n"),
  },
  {
    id: "feature.item-types",
    title: "Turn on more item types",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.item-types"',
      'say "A minimal vault holds secrets and files. The Item types section adds the rest: account, note, card and the other built-in kinds, passkeys as vault items, and X.509 certificates."',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.item-types"',
      'focus "feature.item-types" "The Item types section. Its switch adds all three; the tiles under it switch Derived item types, Passkey records and Certificate records one at a time." side=bottom',
      'say "Each kind can then be chosen when you add an item. An item type is a manifest, never code."',
      'success "That is Item types."',
      "end",
    ].join("\n"),
  },
  {
    id: "feature.environments",
    title: "Turn on Environments",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.environments"',
      'say "Environments give a vault item named values, so one item can carry a value for each place it is used."',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.environments"',
      'focus "feature.environments" "The Environments section. Its switch adds named values to vault items." side=bottom',
      'say "With it on, vault items can carry named values."',
      'success "That is Environments."',
      "end",
    ].join("\n"),
  },
  {
    id: "feature.security-checks",
    title: "Turn on breach and two-step checks",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.security-checks"',
      'say "This check finds passwords that have appeared in a known breach, and sites that take an authenticator code you have not stored."',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.security-checks"',
      'focus "feature.security-checks" "The Breach and two-step checks section. Its switch adds the check." side=bottom',
      'say "Only five characters of each password\'s hash leave the browser, and only when you press Check."',
      'success "That is breach and two-step checks."',
      "end",
    ].join("\n"),
  },
  {
    id: "feature.sharing",
    title: "Turn on Sharing",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.sharing"',
      'say "Sharing lets you hand chosen vault items, or the whole vault, to someone else. Live sessions are browser to browser, paired by codes you pass each other, for as long as the tab stays open. Trusted contacts are the people who, as a circle, approve a request or hold a share of a recovery key."',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.sharing"',
      'focus "feature.sharing" "The Sharing section. Its switch adds live sessions and trusted contacts." side=bottom',
      'say "No server is needed for a live session, and nothing of one is stored on either side. Routes you name — a tunnel address, STUN or TURN — are optional. A circle\'s invitations and answers are packets you pass by hand, and each contact answers with their own security key."',
      'success "That is Sharing."',
      "end",
    ].join("\n"),
  },
  {
    id: "feature.payments",
    title: "Turn on the Wallet",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.payments"',
      'say "The Wallet holds budgets, payment methods and spending passes, with a local ledger that conserves what was spent. An agent can be given a budget; it is never given a card number."',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.payments"',
      'focus "feature.payments" "The Payments section. Its switch adds the Wallet screen; the tiles under it are the issuers you can connect." side=bottom',
      'say "With Payments on, a Wallet screen joins the section list. Payment authorization is in scope here; payment credentials never are."',
      'success "That is Payments."',
      "end",
    ].join("\n"),
  },
  {
    id: "feature.password-reset",
    title: "Turn on Password reset",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.password-reset"',
      'say "Password reset finds a reset message in a mailbox you configure and runs a website\'s reset ceremony for that account, so a stored password can be rotated without you doing each step."',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.password-reset"',
      'focus "feature.password-reset" "The Password reset section. Its switch adds it to this installation." side=bottom',
      'say "Which model runs the reset is a choice in the AI section. The new password is sealed in the vault; it is never shown to an agent."',
      'success "That is Password reset."',
      "end",
    ].join("\n"),
  },
  {
    id: "feature.notifications",
    title: "Turn on Notifications",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.notifications"',
      'say "Notifications decide where you hear that a request is waiting: Web Push, and the order each kind of request tries its channels. Where you are told never changes what it takes to approve."',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.notifications"',
      'focus "feature.notifications" "The Notifications section. Its switch adds Web Push and notification routing." side=bottom',
      'say "With it on, Settings gains a Notifications category, where each kind of request has its own order of channels."',
      'success "That is Notifications."',
      "end",
    ].join("\n"),
  },
  {
    id: "feature.telemetry",
    title: "Telemetry",
    routes: ["/settings"],
    libraryOnly: true,
    guide: [
      "guide/1",
      'goal "feature.telemetry"',
      'say "Telemetry sends anonymous usage and error reports to a collector your operator configures. It is off until someone chooses it."',
      'navigate "/settings/capabilities"',
      'wait route "/settings/capabilities" timeout=15000',
      'scroll "feature.telemetry"',
      'focus "feature.telemetry" "The Telemetry section. Nothing is sent unless it is chosen and a collector is configured." side=bottom',
      'say "A deployment with no collector configured has nowhere to send anything."',
      'success "That is Telemetry."',
      "end",
    ].join("\n"),
  },
];

/**
 * The tutorial each section of Settings › Capabilities opens: its own tour
 * above, or the task-shaped tour that already covers it.
 */
export const FEATURE_TUTORIALS = {
  identity: "feature.identity",
  access: "feature.access",
  connections: "feature.connections",
  directory: "feature.directory",
  encryption: "feature.encryption",
  certificates: "feature.certificates",
  backups: "settings.backup",
  "password-managers": "feature.password-managers",
  "cloud-secret-storage": "feature.cloud-secret-storage",
  "local-storage": "feature.local-storage",
  "encrypted-search": "feature.encrypted-search",
  "item-types": "feature.item-types",
  environments: "feature.environments",
  "security-checks": "feature.security-checks",
  autofill: "settings.browser-autofill",
  sharing: "feature.sharing",
  payments: "feature.payments",
  ai: "settings.model-provider",
  "password-reset": "feature.password-reset",
  surrogates: "settings.surrogate-credentials",
  networking: "settings.tailnet-sync",
  notifications: "feature.notifications",
  "local-notifications": "settings.local-notifications",
  telemetry: "feature.telemetry",
} as const;
