/**
 * Goals and authored help the `identity.*` capabilities contribute
 * (`tutorial-goal` and help-topic contributions, registered on activation).
 */

import type { GuideGoalDescriptor, HelpTopic } from "./goals.js";

export const IDENTITY_GOALS: readonly GuideGoalDescriptor[] = [
  {
    id: "identity.local.requests.manage",
    title: "Create and decide local requests",
    routes: ["/access"],
    guide: [
      "guide/1",
      'goal "identity.local.requests.manage"',
      'navigate "/access"',
      'wait route "/access" timeout=15000',
      'say "Open Requests and choose New local request. Authenticate the requester, choose a registered application and exact callback, then enter scopes and a reason. Review the exact request before approving or denying with a human owner or administrator passkey. Approval does not bypass policy or execute the requesting operation. Pending authority can be withdrawn; terminal history can be removed. No backend is required."',
      "end",
    ].join("\n"),
  },
  {
    id: "identity.local.policy.manage",
    title: "Set local application scope policies",
    routes: ["/access"],
    guide: [
      "guide/1",
      'goal "identity.local.policy.manage"',
      'navigate "/access"',
      'wait route "/access" timeout=15000',
      'say "Open Policies, choose a local application, then expand Application registration. Roles allowed per scope determines who may request each permission. Unchecked roles are denied, even owners. Save registration persists the same encrypted configuration used by Identity. Changes invalidate existing grants; new access still needs sign-in and explicit consent. No extra service is required."',
      "end",
    ].join("\n"),
  },
  {
    id: "identity.local.access.manage",
    title: "Review and revoke local access",
    routes: ["/access"],
    guide: [
      "guide/1",
      'goal "identity.local.access.manage"',
      'navigate "/access"',
      'wait route "/access" timeout=15000',
      'say "Open Grants to inspect this vault’s application grants, or Sessions to include local sign-in sessions. These unexpired records do not prove an application is still connected. Select Revoke on the exact record, then confirm or cancel. Revoking a session invalidates grants that depend on it. Everything stays on this device."',
      "end",
    ].join("\n"),
  },
  {
    id: "identity.local.agent.keys.manage",
    title: "Enroll and authenticate a local agent key",
    routes: ["/identity"],
    guide: [
      "guide/1",
      'goal "identity.local.agent.keys.manage"',
      'navigate "/identity"',
      'wait route "/identity" timeout=15000',
      'focus "identity.agents" "Open an agent’s Agent keys disclosure. Enroll its public ES256 JWK, never its private key. Authenticate agent creates a one-use challenge for the agent to sign; paste only its signed response and verify it. Machine sign-in is not human approval or application access. Sign out agent ends the session; revoking its key also invalidates that enrollment’s sessions." side=bottom',
      'wait target "identity.agents" event=activate timeout=60000',
    ].join("\n"),
  },
  {
    id: "identity.local.application.authorize",
    title: "Review a browser-local application sign-in",
    routes: ["/identity"],
    guide: [
      "guide/1",
      'goal "identity.local.application.authorize"',
      'say "Start sign-in from the registered application. In its OpenSesame window, check the exact requesting site and permissions, choose a local person, then verify an enrolled passkey. Verification alone does not approve access."',
      'say "For agent access, also check the named agent and enrolled key. An organization owner or admin verifies a passkey, then chooses Allow agent access or Deny. Otherwise choose Allow application or Deny. Keep the approved window open; locking the vault or ending the session closes access. This is browser-local identity, not a hosted OIDC service."',
      "end",
    ].join("\n"),
  },
  {
    id: "identity.local.passkeys.manage",
    title: "Manage a local identity's passkeys",
    routes: ["/identity"],
    guide: [
      "guide/1",
      'goal "identity.local.passkeys.manage"',
      'navigate "/identity"',
      'wait route "/identity" timeout=15000',
      'focus "identity.people" "Without an Identity endpoint, open a person’s Passkeys disclosure in People. Enroll a passkey, sign in locally, sign out or confirm revocation. Devices is machine inventory, not authenticators. Sign-in requires authenticator user verification and does not grant application access." side=bottom',
      'wait target "identity.people" event=activate timeout=60000',
    ].join("\n"),
  },
  {
    id: "identity.local.directory.manage",
    title: "Manage this vault's local directory",
    routes: ["/identity"],
    guide: [
      "guide/1",
      'goal "identity.local.directory.manage"',
      'navigate "/identity"',
      'wait route "/identity" timeout=15000',
      'focus "identity.people" "Without an Identity endpoint, manage encrypted local records here. People can enroll passkeys and sign in locally. In Organization, open Members to assign an owner, add members or change roles. Keep an enabled human owner; roles do not grant connector or application access." side=bottom',
      'wait target "identity.people" event=activate timeout=60000',
    ].join("\n"),
  },
  {
    id: "identity.account.add",
    title: "Add an account to this deployment",
    routes: [],
    guide: [
      "guide/1",
      'goal "identity.account.add"',
      'say "Accounts are vouched for by an identity provider, so a provider is registered before anyone signs in through it."',
      'navigate "/identity"',
      'wait route "/identity" timeout=15000',
      'focus "identity.providers" "Providers lists whoever may vouch for people here." side=bottom',
      'wait target "identity.register-idp" event=activate timeout=60000',
    ].join("\n"),
  },
  {
    id: "identity.users.manage",
    title: "Manage organization users",
    routes: ["/identity"],
    guide: [
      "guide/1",
      'goal "identity.users.manage"',
      'navigate "/identity"',
      'wait route "/identity" timeout=15000',
      'focus "identity.people" "Open People, select an organization you own, then create or edit a directory user. Provisioning does not replace verified sign-in." side=bottom',
      'wait target "identity.people" event=activate timeout=60000',
    ].join("\n"),
  },
  {
    id: "identity.agents.manage",
    title: "Manage agent registrations",
    routes: ["/identity"],
    guide: [
      "guide/1",
      'goal "identity.agents.manage"',
      'navigate "/identity"',
      'wait route "/identity" timeout=15000',
      'focus "identity.agents" "Open Agents to register a runtime public-key thumbprint, rename a registration or revoke one you own. Never paste a private key." side=bottom',
      'wait target "identity.agents" event=activate timeout=60000',
    ].join("\n"),
  },
  {
    id: "identity.local.siop.authorize",
    title: "Approve a Self-Issued OpenID Provider sign-in",
    routes: ["/identity"],
    guide: [
      "guide/1",
      'goal "identity.local.siop.authorize"',
      'say "When a relying party asks this device to sign in as itself, review the exact client and claims on Identity. Verify an enrolled passkey, then allow or deny. The Self-Issued ID Token never leaves the vault as a reusable secret."',
      "end",
    ].join("\n"),
  },
  {
    id: "authority.portal.templates.manage",
    title: "Install or revise Access portal authority templates",
    routes: ["/access"],
    guide: [
      "guide/1",
      'goal "authority.portal.templates.manage"',
      'navigate "/access"',
      'wait route "/access" timeout=15000',
      'say "Open Access and review Audience templates. Installing or revising a template shapes the vocabulary and default limits for temporary domains or sessions. Selecting a template does not issue a grant."',
      "end",
    ].join("\n"),
  },
  {
    id: "authority.portal.templates.read",
    title: "Read Access portal authority templates",
    routes: ["/access"],
    guide: [
      "guide/1",
      'goal "authority.portal.templates.read"',
      'navigate "/access"',
      'wait route "/access" timeout=15000',
      'say "Audience templates list the versioned vocabulary and default limits available on Access. Reading them does not change grants or enforcement."',
      "end",
    ].join("\n"),
  },

  {
    id: "identity.device.approve",
    title: "Approve a device sign-in",
    routes: [],
    guide: [
      "guide/1",
      'goal "identity.device.approve"',
      'wait state "vault.unlocked" is=true timeout=60000',
      'navigate "/identity"',
      'wait route "/identity" timeout=15000',
      'focus "identity.devices" "Device sign-ins waiting for a person are listed here." side=bottom',
      "end",
    ].join("\n"),
  },
];

export const IDENTITY_HELP: readonly HelpTopic[] = [
  {
    id: "help.identity.account.add",
    title: "How do I add someone to this deployment?",
    answer:
      "Identity → Providers, then Register an IdP. People sign in through a registered identity provider, so the provider is bound first; the shipped presets cover the common enterprise issuers and a custom OIDC issuer is the fallback.",
    routes: [],
    goal: "identity.account.add",
    keywords: [
      "user",
      "users",
      "person",
      "people",
      "someone",
      "member",
      "members",
      "team",
      "invite",
      "add account",
      "account",
      "sign in",
      "sign-in",
      "idp",
      "provider",
      "register",
      "deployment",
      "onboard",
      "seat",
      "colleague",
    ],
  },
  {
    id: "help.account.register",
    title: "How do I register a new account?",
    answer:
      "People sign in through a registered identity provider. Identity → Providers → Register an IdP binds the issuer; the sign-in screen then offers it. First-run setup is the same allowlist before anyone has unlocked.",
    routes: [],
    goal: "identity.account.add",
    keywords: [
      "register",
      "sign up",
      "signup",
      "new account",
      "create account",
      "user",
      "account",
      "join",
      "onboard",
      "enroll",
    ],
  },
];
