// Generated by scripts/emit-definitions.mjs — do not edit.
// Source of truth: marketplace/item-types/builtin/*.json

/** What the app knows of a pack without having fetched it. */
export type PackEntry = {
  readonly id: string;
  readonly title: string;
  readonly plural: string;
  readonly extension: string;
  readonly summary: string;
  readonly categories: readonly string[];
  readonly version: string;
  readonly fields: number;
  /** UTF-8 length of the definition text: the size of the download. */
  readonly bytes: number;
  /** Hex SHA-256 of the definition text, checked before it is parsed. */
  readonly sha256: string;
};

export const PACK_INDEX: readonly PackEntry[] = [
  {"id":"account","title":"Account","plural":"Accounts","extension":".account","summary":"A username or id, the sites it signs into, and the ways it logs in.","categories":["access"],"version":"1.0.0","fields":4,"bytes":1276,"sha256":"a5db2e0c1f3c444368dddc3ade3ff96b310b2c4cc403ff24056e9d5430e8e746"},
  {"id":"address","title":"Address","plural":"Addresses","extension":".address","summary":"A postal address, for filling in the forms that keep asking for one.","categories":["identity"],"version":"1.0.0","fields":3,"bytes":1115,"sha256":"fc5ce9d6cbdb73780a60d2917c38ff46cac352ed5076581a6cfcaaeb98d8f479"},
  {"id":"api-credential","title":"API credential","plural":"API credentials","extension":".api","summary":"An API key or client credential, and the endpoint and scopes it is good for.","categories":["developer","access"],"version":"1.0.0","fields":9,"bytes":2196,"sha256":"c4fcadfa143ee6cca870832816c83092ab547e6e4af59c2c254ec461dd501edd"},
  {"id":"api-key","title":"API key","plural":"API keys","extension":".apikey","summary":"An API key and the header it travels in, kept on its own or bound to an account.","categories":["developer","access"],"version":"1.0.0","fields":2,"bytes":1071,"sha256":"3778e7c8b0b74389be67e60263188d9b044eb53db2ed8ca08860dba2c0c5f37f"},
  {"id":"authenticator","title":"Authenticator","plural":"Authenticators","extension":".totp","summary":"A one-time code seed, kept on its own or bound to the account it opens.","categories":["access"],"version":"1.0.0","fields":1,"bytes":896,"sha256":"982e963382ddfde50511c32dd543890d26bc69c6c7c2eacf8b5e3d2b725bfeea"},
  {"id":"bank-account","title":"Bank account","plural":"Bank accounts","extension":".bank","summary":"Account and routing numbers, the branch they belong to, and the PIN that goes with them.","categories":["finance"],"version":"1.0.0","fields":11,"bytes":2641,"sha256":"dbf04eaac7f8eadc709cf32af837391aa1b7f64acb06066200c24c943149e7db"},
  {"id":"card","title":"Card","plural":"Cards","extension":".card","summary":"A payment card: the number, who it belongs to, and when it expires.","categories":["finance"],"version":"1.0.0","fields":6,"bytes":1372,"sha256":"188ead11f2f795f7ceb7087c1a8b862dedeacd05c44e50080ba41239e0cbe911"},
  {"id":"contact","title":"Contact","plural":"Contacts","extension":".contact","summary":"A person and how to reach them, kept beside the credentials that involve them.","categories":["identity"],"version":"1.0.0","fields":7,"bytes":1781,"sha256":"085ad1ca37e157f65559992f967dbdf45186217f5269ed4e28efe105516785bc"},
  {"id":"crypto-wallet","title":"Crypto wallet","plural":"Crypto wallets","extension":".wallet","summary":"A wallet's recovery phrase, its addresses, and the network it lives on.","categories":["finance"],"version":"1.0.0","fields":7,"bytes":1893,"sha256":"c41387aab56727a147a019e7e31a2b42e1b66a2104e55c3be11393ad71662fdd"},
  {"id":"database","title":"Database","plural":"Databases","extension":".db","summary":"Connection details for a database, and the credential that opens it.","categories":["developer","access"],"version":"1.0.0","fields":9,"bytes":2673,"sha256":"526de236c64ff609bc9c5364c8aca9b3a76cd53d58d09b369001e284c896a9fe"},
  {"id":"drivers-license","title":"Driving licence","plural":"Driving licences","extension":".dl","summary":"A driving licence, following the mandatory data fields of ISO 18013-1.","categories":["identity","documents"],"version":"1.0.0","fields":10,"bytes":2411,"sha256":"fc3b80b8eec06f35985402839c551a1161d77c386b407fbc472ca9637d478c6d"},
  {"id":"health-insurance","title":"Health insurance","plural":"Health insurance","extension":".health","summary":"A member id, the plan it belongs to, and who to call about it.","categories":["identity","documents"],"version":"1.0.0","fields":11,"bytes":2307,"sha256":"a81da5503837ecfb9b2f832860bcb510c9bc15e5dc10ddb03af16145a628f23f"},
  {"id":"identity-document","title":"Identity document","plural":"Identity documents","extension":".id","summary":"A national ID, resident card, tax identification or social security number.","categories":["identity","documents"],"version":"1.0.0","fields":9,"bytes":2213,"sha256":"cfc82a7ee17c2cce7efb43796eba11e70101ff8b9035f09767725d1d3c2dd4d3"},
  {"id":"membership","title":"Membership","plural":"Memberships","extension":".member","summary":"A loyalty, club or professional membership and the number that proves it.","categories":["identity"],"version":"1.0.0","fields":8,"bytes":1897,"sha256":"6981f61d74456b6b807c2dde3a266f3592531d10a465f4630162a90cd26e7a0f"},
  {"id":"note","title":"Secure note","plural":"Secure notes","extension":".note","summary":"Free text, sealed with everything else in the vault.","categories":["documents"],"version":"1.0.0","fields":1,"bytes":728,"sha256":"17cba906a561c0561629b886450def2e2608500ce6c94066f6be362cad0456d1"},
  {"id":"oauth-client","title":"OAuth client","plural":"OAuth clients","extension":".oauth","summary":"An OAuth client id and secret, its token endpoint and scopes, kept on its own or bound to an account.","categories":["developer","access"],"version":"1.0.0","fields":5,"bytes":1713,"sha256":"d325fdd77581b3bc2d42b502196095856fdeb50752fc4e69bf2f87295f4adcca"},
  {"id":"passport","title":"Passport","plural":"Passports","extension":".passport","summary":"A travel document, following the data elements of ICAO Doc 9303.","categories":["identity","documents"],"version":"1.0.0","fields":11,"bytes":2637,"sha256":"913e7ed2c11100634e72a684af6407760fb88b99a69ceeaefd7554fc18e89084"},
  {"id":"password","title":"Password","plural":"Passwords","extension":".password","summary":"A password, kept on its own or bound to the account it opens.","categories":["access"],"version":"1.0.0","fields":1,"bytes":800,"sha256":"fdc3ae096da53521c2db226eb143b03a0c5dfde00d31b331ed851f426aad3610"},
  {"id":"server","title":"Server","plural":"Servers","extension":".server","summary":"A machine, the account that reaches it, and how to get in.","categories":["developer","access"],"version":"1.0.0","fields":9,"bytes":2240,"sha256":"be9c0233885792bd667e3566b3eb9e17125f7aa0cc94c52e45eed77b3adf0226"},
  {"id":"software-license","title":"Software licence","plural":"Software licences","extension":".license","summary":"A licence key, who it is registered to, and what it entitles.","categories":["finance","documents"],"version":"1.0.0","fields":10,"bytes":2233,"sha256":"a378cde36b122934629368e6342a13d9fde803a80c8d1694e7040dd27ae8cefa"},
  {"id":"ssh-key","title":"SSH key","plural":"SSH keys","extension":".ssh","summary":"An SSH key pair, its fingerprint, and the hosts it opens.","categories":["access","developer"],"version":"1.0.0","fields":7,"bytes":1765,"sha256":"22ed91e658799e8e8833aa8b40722f6f21655411429684ffda597f054457fc77"},
  {"id":"token","title":"Token","plural":"Tokens","extension":".token","summary":"A bearer token and when it lapses, kept on its own or bound to an account.","categories":["developer","access"],"version":"1.0.0","fields":2,"bytes":1012,"sha256":"09a5e8fa3d57f6c7f3c5ca0c9d1e681a50e3e84588b77e1a73a62b35c59e2d24"},
  {"id":"wifi","title":"Wi-Fi network","plural":"Wi-Fi networks","extension":".wifi","summary":"A network name, its passphrase, and how it is secured.","categories":["access"],"version":"1.0.0","fields":6,"bytes":1723,"sha256":"868e6bd6ee0c4b2d8683f4df21430b24120d6f29f45c6e52454d31cd5a2a5211"},
];

/** One dynamic import per pack, so each is its own chunk. */
export const PACK_LOADERS = new Map([
  ["account", () => import("./packs/account.generated.js")],
  ["address", () => import("./packs/address.generated.js")],
  ["api-credential", () => import("./packs/api-credential.generated.js")],
  ["api-key", () => import("./packs/api-key.generated.js")],
  ["authenticator", () => import("./packs/authenticator.generated.js")],
  ["bank-account", () => import("./packs/bank-account.generated.js")],
  ["card", () => import("./packs/card.generated.js")],
  ["contact", () => import("./packs/contact.generated.js")],
  ["crypto-wallet", () => import("./packs/crypto-wallet.generated.js")],
  ["database", () => import("./packs/database.generated.js")],
  ["drivers-license", () => import("./packs/drivers-license.generated.js")],
  ["health-insurance", () => import("./packs/health-insurance.generated.js")],
  ["identity-document", () => import("./packs/identity-document.generated.js")],
  ["membership", () => import("./packs/membership.generated.js")],
  ["note", () => import("./packs/note.generated.js")],
  ["oauth-client", () => import("./packs/oauth-client.generated.js")],
  ["passport", () => import("./packs/passport.generated.js")],
  ["password", () => import("./packs/password.generated.js")],
  ["server", () => import("./packs/server.generated.js")],
  ["software-license", () => import("./packs/software-license.generated.js")],
  ["ssh-key", () => import("./packs/ssh-key.generated.js")],
  ["token", () => import("./packs/token.generated.js")],
  ["wifi", () => import("./packs/wifi.generated.js")],
]);
