//! Disposable PKI generated by the **system `openssl` CLI**.
//!
//! This is deliberately not `opensesame_transport_security::testkit`: an
//! oracle that issues certificates with the same `rcgen` the production
//! verifiers were developed against can only repeat that library's
//! assumptions. Everything here comes out of OpenSSL 3, and every file lives
//! in a [`tempfile::TempDir`] that is removed when the [`Pki`] drops.
//!
//! Validity windows are explicit and short (hours, not years) so an expiry
//! fixture is real rather than simulated, and so nothing generated here is
//! useful if it ever escaped the temporary directory.

mod spec;

pub use spec::{LeafSpec, Window};

use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{bail, Context as _, Result};

/// One certificate authority: its key, its self-signed or issued certificate,
/// and the chain a peer must present to be verified against the root.
pub struct Ca {
    dir: PathBuf,
    name: String,
    /// `<name>.pem` — this authority's own certificate.
    pub cert: PathBuf,
    key: PathBuf,
    /// Root-first bundle a verifier trusts to reach this authority.
    pub anchors: PathBuf,
    /// The intermediates a leaf of this authority must ship (may be empty).
    chain: Vec<PathBuf>,
}

/// One end-entity certificate plus the files a client or server loads.
pub struct Leaf {
    /// Leaf first, then every intermediate below the root.
    pub chain: PathBuf,
    /// The leaf on its own, no issuers.
    pub cert: PathBuf,
    /// PKCS#8 private key.
    pub key: PathBuf,
    /// The issuers between the leaf and the root, without the leaf. `None`
    /// when a root issued the leaf directly.
    ///
    /// `openssl s_client -cert <file>` sends only the *first* certificate in
    /// the file, so an intermediate chain has to be handed to it separately
    /// through `-cert_chain`. rustls and Node both take the whole
    /// leaf-first bundle instead; keeping both spellings is what lets the
    /// three stacks present the same identity.
    pub intermediates: Option<PathBuf>,
    /// Lowercase hex SHA-256 of the leaf's DER — the contract's thumbprint.
    pub thumbprint: String,
}

/// A whole disposable world: several unrelated roots, under one temp dir.
pub struct Pki {
    dir: tempfile::TempDir,
}

fn openssl(dir: &Path, args: &[&str]) -> Result<Vec<u8>> {
    let out = Command::new("/usr/bin/openssl")
        .current_dir(dir)
        .args(args)
        .output()
        .with_context(|| format!("spawn openssl {}", args.join(" ")))?;
    if !out.status.success() {
        bail!(
            "openssl {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr)
        );
    }
    Ok(out.stdout)
}

fn write(path: &Path, bytes: &[u8]) -> Result<()> {
    std::fs::write(path, bytes).with_context(|| format!("write {}", path.display()))
}

fn concat(dir: &Path, name: &str, parts: &[&Path]) -> Result<PathBuf> {
    let mut buf = Vec::new();
    for part in parts {
        buf.extend_from_slice(&std::fs::read(part).with_context(|| format!("{}", part.display()))?);
        if !buf.ends_with(b"\n") {
            buf.push(b'\n');
        }
    }
    let path = dir.join(name);
    write(&path, &buf)?;
    Ok(path)
}

impl Pki {
    /// A fresh temporary world.
    ///
    /// # Errors
    ///
    /// The temporary directory could not be created.
    pub fn new() -> Result<Self> {
        Ok(Self {
            dir: tempfile::Builder::new()
                .prefix("opensesame-iop-pki-")
                .tempdir()?,
        })
    }

    /// The directory every generated file lives in.
    #[must_use]
    pub fn dir(&self) -> &Path {
        self.dir.path()
    }

    /// A self-signed root. Two roots from the same [`Pki`] share nothing but
    /// the directory, which is exactly what "distinct trust root" must mean.
    ///
    /// # Errors
    ///
    /// `openssl` refused to generate the key or the certificate.
    pub fn root(&self, name: &str) -> Result<Ca> {
        let dir = self.dir.path().to_path_buf();
        let key = dir.join(format!("{name}.key"));
        let cert = dir.join(format!("{name}.pem"));
        openssl(
            &dir,
            &[
                "ecparam",
                "-name",
                "prime256v1",
                "-genkey",
                "-noout",
                "-out",
                &key.to_string_lossy(),
            ],
        )?;
        openssl(
            &dir,
            &[
                "req",
                "-x509",
                "-new",
                "-key",
                &key.to_string_lossy(),
                "-sha256",
                "-days",
                "1",
                "-subj",
                &format!("/CN={name}"),
                "-addext",
                "basicConstraints=critical,CA:TRUE",
                "-addext",
                "keyUsage=critical,keyCertSign,cRLSign",
                "-out",
                &cert.to_string_lossy(),
            ],
        )?;
        Ok(Ca {
            dir,
            name: name.to_string(),
            anchors: cert.clone(),
            cert,
            key,
            chain: Vec::new(),
        })
    }
}

impl Ca {
    /// An intermediate CA signed by this authority. Leaves it issues ship the
    /// whole chain; verifiers still anchor on the root.
    ///
    /// # Errors
    ///
    /// `openssl` refused to generate or sign the intermediate.
    pub fn intermediate(&self, name: &str) -> Result<Ca> {
        let key = self.dir.join(format!("{name}.key"));
        let csr = self.dir.join(format!("{name}.csr"));
        let cert = self.dir.join(format!("{name}.pem"));
        let ext = self.dir.join(format!("{name}.ext"));
        openssl(
            &self.dir,
            &[
                "ecparam",
                "-name",
                "prime256v1",
                "-genkey",
                "-noout",
                "-out",
                &key.to_string_lossy(),
            ],
        )?;
        openssl(
            &self.dir,
            &[
                "req",
                "-new",
                "-key",
                &key.to_string_lossy(),
                "-subj",
                &format!("/CN={name}"),
                "-out",
                &csr.to_string_lossy(),
            ],
        )?;
        write(
            &ext,
            b"basicConstraints=critical,CA:TRUE,pathlen:0\n\
              keyUsage=critical,keyCertSign,cRLSign\n\
              subjectKeyIdentifier=hash\n",
        )?;
        self.sign(&csr, &cert, &ext)?;
        let mut chain = self.chain.clone();
        chain.insert(0, cert.clone());
        Ok(Ca {
            dir: self.dir.clone(),
            name: name.to_string(),
            cert,
            key,
            anchors: self.anchors.clone(),
            chain,
        })
    }

    fn sign(&self, csr: &Path, cert: &Path, ext: &Path) -> Result<()> {
        openssl(
            &self.dir,
            &[
                "x509",
                "-req",
                "-in",
                &csr.to_string_lossy(),
                "-CA",
                &self.cert.to_string_lossy(),
                "-CAkey",
                &self.key.to_string_lossy(),
                "-CAcreateserial",
                "-days",
                "1",
                "-sha256",
                "-extfile",
                &ext.to_string_lossy(),
                "-out",
                &cert.to_string_lossy(),
            ],
        )?;
        Ok(())
    }

    /// Issue an end-entity certificate from a [`LeafSpec`].
    ///
    /// # Errors
    ///
    /// `openssl` refused any step, or the leaf could not be hashed.
    pub fn issue(&self, spec: &LeafSpec) -> Result<Leaf> {
        let stem = format!("{}-{}", self.name, spec.name);
        let key = self.dir.join(format!("{stem}.key"));
        let csr = self.dir.join(format!("{stem}.csr"));
        let cert = self.dir.join(format!("{stem}.pem"));
        let ext = self.dir.join(format!("{stem}.ext"));
        openssl(
            &self.dir,
            &[
                "genpkey",
                "-algorithm",
                "EC",
                "-pkeyopt",
                "ec_paramgen_curve:P-256",
                "-out",
                &key.to_string_lossy(),
            ],
        )?;
        openssl(
            &self.dir,
            &[
                "req",
                "-new",
                "-key",
                &key.to_string_lossy(),
                "-subj",
                &format!("/CN={}", spec.name),
                "-out",
                &csr.to_string_lossy(),
            ],
        )?;
        write(&ext, spec.extensions().as_bytes())?;
        self.sign_windowed(&csr, &cert, &ext, spec)?;
        let chain_files: Vec<&Path> = std::iter::once(cert.as_path())
            .chain(self.chain.iter().map(PathBuf::as_path))
            .collect();
        let chain = concat(&self.dir, &format!("{stem}-chain.pem"), &chain_files)?;
        let intermediates = if self.chain.is_empty() {
            None
        } else {
            let parts: Vec<&Path> = self.chain.iter().map(PathBuf::as_path).collect();
            Some(concat(
                &self.dir,
                &format!("{stem}-intermediates.pem"),
                &parts,
            )?)
        };
        let thumbprint = thumbprint_of(&self.dir, &cert)?;
        Ok(Leaf {
            chain,
            cert,
            key,
            intermediates,
            thumbprint,
        })
    }

    /// OpenSSL 3.0's `x509 -req` has no `-not_before`/`-not_after` (they
    /// arrive in 3.4), so an out-of-window leaf goes through `openssl ca`,
    /// which has taken `-startdate`/`-enddate` for decades. The database it
    /// needs is created per authority inside the same temporary directory.
    fn sign_windowed(&self, csr: &Path, cert: &Path, ext: &Path, spec: &LeafSpec) -> Result<()> {
        if spec.window == Window::Valid {
            return self.sign(csr, cert, ext);
        }
        let db = self.dir.join(format!("{}-cadb", self.name));
        let conf = self.dir.join(format!("{}-ca.cnf", self.name));
        if !db.exists() {
            std::fs::create_dir_all(&db)?;
            write(&db.join("index.txt"), b"")?;
            write(&db.join("serial"), b"01\n")?;
            write(
                &conf,
                format!(
                    "[ca]\ndefault_ca=d\n[d]\ndir=.\ndatabase={0}/index.txt\nserial={0}/serial\n\
                     new_certs_dir={0}\ndefault_md=sha256\npolicy=p\nemail_in_dn=no\n\
                     rand_serial=no\nunique_subject=no\ncopy_extensions=none\n\
                     [p]\ncommonName=supplied\n",
                    db.display()
                )
                .as_bytes(),
            )?;
        }
        let (start, end) = spec.window.absolute();
        openssl(
            &self.dir,
            &[
                "ca",
                "-batch",
                "-notext",
                "-config",
                &conf.to_string_lossy(),
                "-cert",
                &self.cert.to_string_lossy(),
                "-keyfile",
                &self.key.to_string_lossy(),
                "-in",
                &csr.to_string_lossy(),
                "-out",
                &cert.to_string_lossy(),
                "-startdate",
                &start,
                "-enddate",
                &end,
                "-extfile",
                &ext.to_string_lossy(),
            ],
        )?;
        Ok(())
    }

    /// A leaf whose public certificate is this one but whose key file is
    /// another leaf's: the private-key-possession fixture.
    ///
    /// # Errors
    ///
    /// The substitute key could not be written.
    pub fn mismatched_key(&self, cert_of: &Leaf, key_of: &Leaf, name: &str) -> Result<Leaf> {
        let key = self.dir.join(format!("{name}-substituted.key"));
        std::fs::copy(&key_of.key, &key)?;
        Ok(Leaf {
            chain: cert_of.chain.clone(),
            cert: cert_of.cert.clone(),
            key,
            intermediates: cert_of.intermediates.clone(),
            thumbprint: cert_of.thumbprint.clone(),
        })
    }
}

fn thumbprint_of(dir: &Path, cert: &Path) -> Result<String> {
    let out = openssl(
        dir,
        &[
            "x509",
            "-in",
            &cert.to_string_lossy(),
            "-outform",
            "DER",
            "-fingerprint",
            "-sha256",
            "-noout",
        ],
    )?;
    let text = String::from_utf8_lossy(&out);
    let hex = text
        .split('=')
        .nth(1)
        .context("openssl fingerprint had no value")?;
    Ok(hex.trim().replace(':', "").to_lowercase())
}
