[package]
name = "opensesame-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
opensesame-domain = { path = "../domain" }
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
insta = { workspace = true, features = ["redactions", "json"] }
proptest = { workspace = true }
futures = { workspace = true }
