[package]
name = "opensesame-connector-host"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
opensesame-domain = { path = "../domain" }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }
