/**
 * A nats-server that live sessions can mint credentials for (ADR 0167): an
 * operator, its system account, and one account whose signing key the owner
 * puts in Routes. The server runs in operator mode with the accounts
 * preloaded (`resolver: MEMORY`), so it trusts any user the signing key
 * issues — and only for what that user's token allows, until it expires.
 *
 * Nothing here touches a disk or a network: it returns the configuration
 * text and the keys, and the caller (`scripts/dev/live-nats-operator.ts`,
 * `verify:live-join`) decides where they go. The operator's seed is
 * returned so an operator can re-issue the account; it belongs offline.
 */

import { createAccount, createOperator, createUser } from "@nats-io/nkeys";
import type { NatsCredential } from "./nats-credentials.js";
import {
  encodeAccountJwt,
  encodeOperatorJwt,
  encodeUserJwt,
} from "./nats-jwt.js";
import type { NatsMint } from "./nats-route.js";

export type LiveNatsOperatorInput = Readonly<{
  /** The WebSocket listener, `host:port`. */
  websocket: string;
  /** The client listener, `host:port`; loopback on a free port if omitted. */
  listen?: string;
  /** A certificate and key for `wss://`; plain `ws://` (loopback only) if omitted. */
  tls?: Readonly<{ cert: string; key: string }>;
  /** The account's name. */
  name?: string;
  /** Also issue a credential on every subject of the account (a test's console). */
  watcher?: boolean;
}>;

export type LiveNatsOperator = Readonly<{
  /** The nats-server configuration. */
  config: string;
  /** What the owner puts in Routes › NATS server › Sign-in. */
  mint: NatsMint;
  /** The operator's seed, to keep offline. */
  operatorSeed: string;
  /** With `watcher`: a `.creds`-style user on every subject (for a test). */
  watcher?: NatsCredential;
}>;

const decoder = new TextDecoder();
const seedOf = (key: { getSeed(): Uint8Array }) =>
  decoder.decode(key.getSeed());

function websocketBlock(input: LiveNatsOperatorInput): string {
  const tls = input.tls
    ? `  tls {\n    cert_file: ${JSON.stringify(input.tls.cert)}\n    key_file: ${JSON.stringify(input.tls.key)}\n  }`
    : "  no_tls: true";
  return `websocket {\n  listen: ${JSON.stringify(input.websocket)}\n${tls}\n}`;
}

async function watcherFor(
  signer: ReturnType<typeof createAccount>,
  account: string,
): Promise<NatsCredential> {
  const user = createUser();
  const jwt = await encodeUserJwt(
    signer,
    account,
    user.getPublicKey(),
    "watcher",
    { pub: [">"], sub: [">"] },
    Math.ceil(Date.now() / 1000) + 24 * 3600,
  );
  return { jwt, seed: seedOf(user) };
}

export async function liveNatsOperator(
  input: LiveNatsOperatorInput,
): Promise<LiveNatsOperator> {
  const operator = createOperator();
  const system = createAccount();
  const account = createAccount();
  const signer = createAccount();
  const name = input.name ?? "LIVE";
  const operatorJwt = await encodeOperatorJwt(
    operator,
    "opensesame-live",
    system.getPublicKey(),
  );
  const systemJwt = await encodeAccountJwt(
    operator,
    system.getPublicKey(),
    "SYS",
    [],
  );
  const accountJwt = await encodeAccountJwt(
    operator,
    account.getPublicKey(),
    name,
    [signer.getPublicKey()],
  );
  const config = [
    "# OpenSesame live sessions — nats-server in operator mode (ADR 0167).",
    "# Generated by scripts/dev/live-nats-operator.ts; the account signing key",
    "# that issues each session's credential is not in this file.",
    `listen: ${JSON.stringify(input.listen ?? "127.0.0.1:-1")}`,
    websocketBlock(input),
    `operator: ${operatorJwt}`,
    `system_account: ${system.getPublicKey()}`,
    "resolver: MEMORY",
    "resolver_preload: {",
    `  ${system.getPublicKey()}: ${systemJwt}`,
    `  ${account.getPublicKey()}: ${accountJwt}`,
    "}",
    "",
  ].join("\n");
  const mint = { account: account.getPublicKey(), signingKey: seedOf(signer) };
  const issued = { config, mint, operatorSeed: seedOf(operator) };
  if (!input.watcher) return issued;
  return {
    ...issued,
    watcher: await watcherFor(signer, account.getPublicKey()),
  };
}
