[package]
name = "opensesame-rotation"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Rotation state machine"

[dependencies]
opensesame-domain = { path = "../domain" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
