/** @vitest-environment node */
/** Finite HTTP contract + local cryptography, never actual Azure execution. */
import type { ProtectionContext } from "@opensesame/vault-core";
import { expect, it, vi } from "vitest";
import { ProtectionError } from "../errors.js";
import { createAzureKeyVaultKeysHttpsTransport } from "./azure-key-vault-https.js";
import {
  AZURE_WRAP_ALGORITHM,
  createAzureKeyVaultKeysProtector,
} from "./azure-key-vault-keys.js";
import {
  b64ToBytes,
  bytesToB64,
  mintWrappingSecret,
} from "./cloud-wrapping-secret.js";

const KEY_ID =
  "https://generated.vault.azure.net/keys/generated-root/0123456789abcdef0123456789abcdef";
const CONTEXT: ProtectionContext = {
  vaultId: "vault-generated",
  rootKeyId: "root-generated",
  rootEpoch: 1,
  protectorId: "protector-generated",
  purpose: "human-vault-root",
};
async function localRsaPort() {
  const keys = await crypto.subtle.generateKey(
    {
      name: "RSA-OAEP",
      modulusLength: 2048,
      publicExponent: new Uint8Array([1, 0, 1]),
      hash: "SHA-256",
    },
    true,
    ["encrypt", "decrypt"],
  );
  const plainLengths: number[] = [];
  const fetchImpl = vi.fn(
    async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
      const body: unknown = JSON.parse(String(init?.body));
      if (
        typeof body !== "object" ||
        body === null ||
        !("value" in body) ||
        !("alg" in body) ||
        typeof body.value !== "string"
      )
        throw new Error("Generated request malformed");
      expect(body.alg).toBe(AZURE_WRAP_ALGORITHM);
      const bytes = new Uint8Array(b64ToBytes(body.value));
      const url = new URL(String(input));
      let result: ArrayBuffer;
      if (url.pathname.endsWith("/wrapkey")) {
        plainLengths.push(bytes.length);
        result = await crypto.subtle.encrypt(
          { name: "RSA-OAEP" },
          keys.publicKey,
          bytes.buffer,
        );
      } else if (url.pathname.endsWith("/unwrapkey")) {
        result = await crypto.subtle.decrypt(
          { name: "RSA-OAEP" },
          keys.privateKey,
          bytes.buffer,
        );
      } else throw new Error("Generated route refused");
      return Response.json({ value: bytesToB64(new Uint8Array(result)) });
    },
  );
  const transport = createAzureKeyVaultKeysHttpsTransport({
    bearerToken: "generated context",
    apiVersion: "7.5",
    fetchImpl,
  });
  return { transport, fetchImpl, plainLengths };
}

it("uses exact versioned wrap/unwrap URLs and round-trips generated bytes through local RSA", async () => {
  const port = await localRsaPort();
  const plaintext = mintWrappingSecret();
  try {
    const wrapped = await port.transport.wrapKey({
      versionedKeyId: KEY_ID,
      algorithm: AZURE_WRAP_ALGORITHM,
      plaintext,
    });
    expect(wrapped.ciphertext.length).toBe(256);
    const opened = await port.transport.unwrapKey({
      versionedKeyId: KEY_ID,
      algorithm: AZURE_WRAP_ALGORITHM,
      ciphertext: wrapped.ciphertext,
    });
    expect(
      opened.plaintext.every((byte, index) => byte === plaintext[index]),
    ).toBe(true);
    expect(port.plainLengths).toEqual([32]);
    const calls = port.fetchImpl.mock.calls;
    expect(calls.map(([url]) => String(url))).toEqual([
      `${KEY_ID}/wrapkey?api-version=7.5`,
      `${KEY_ID}/unwrapkey?api-version=7.5`,
    ]);
    for (const [, init] of calls) {
      expect(init?.method).toBe("POST");
      const headers = new Headers(init?.headers);
      expect(headers.get("content-type")).toBe("application/json");
      expect(headers.get("authorization") === "Bearer generated context").toBe(
        true,
      );
    }
    opened.plaintext.fill(0);
  } finally {
    plaintext.fill(0);
  }
});

it("protects a real root capsule and refuses a changed original context", async () => {
  const port = await localRsaPort();
  const protector = createAzureKeyVaultKeysProtector({
    transport: port.transport,
    authorization: "authorized",
  });
  const rootKey = mintWrappingSecret();
  try {
    const wrapped = await protector.wrap({
      context: CONTEXT,
      rootKey,
      versionedKeyId: KEY_ID,
      connectionId: "generated-connection",
      connectionConfigVersion: "1",
      tenantId: "generated-tenant",
    });
    expect(port.plainLengths).toEqual([32]);
    expect(wrapped.record.algorithm).toBe(AZURE_WRAP_ALGORITHM);
    const opened = await protector.unwrap({
      context: CONTEXT,
      record: wrapped.record,
    });
    expect(opened.every((byte, index) => byte === rootKey[index])).toBe(true);
    opened.fill(0);
    await expect(
      protector.unwrap({
        context: { ...CONTEXT, rootEpoch: 2 },
        record: wrapped.record,
      }),
    ).rejects.toBeInstanceOf(ProtectionError);
  } finally {
    rootKey.fill(0);
  }
});

const operations = ["wrap", "unwrap"] as const;
function invoke(
  transport: ReturnType<typeof createAzureKeyVaultKeysHttpsTransport>,
  operation: (typeof operations)[number],
  keyId = KEY_ID,
) {
  return operation === "wrap"
    ? transport.wrapKey({
        versionedKeyId: keyId,
        algorithm: AZURE_WRAP_ALGORITHM,
        plaintext: mintWrappingSecret(),
      })
    : transport.unwrapKey({
        versionedKeyId: keyId,
        algorithm: AZURE_WRAP_ALGORITHM,
        ciphertext: crypto.getRandomValues(new Uint8Array(256)),
      });
}
it.each(operations)(
  "%s rejects network failure with its existing transport category",
  async (operation) => {
    const fetchImpl = vi.fn(async (): Promise<Response> => {
      throw new Error("Generated network failure");
    });
    const transport = createAzureKeyVaultKeysHttpsTransport({
      bearerToken: "generated context",
      fetchImpl,
    });
    await expect(invoke(transport, operation)).rejects.toMatchObject({
      code: "unavailable",
    });
    expect(fetchImpl).toHaveBeenCalledOnce();
  },
);
it.each(operations)(
  "%s preserves provider HTTP denial without returning material",
  async (operation) => {
    const fetchImpl = vi.fn(async () =>
      Response.json({ error: "generated refusal" }, { status: 403 }),
    );
    const transport = createAzureKeyVaultKeysHttpsTransport({
      bearerToken: "generated context",
      fetchImpl,
    });
    await expect(invoke(transport, operation)).rejects.toMatchObject({
      code: "provider_denied",
    });
  },
);
it.each(operations)(
  "%s rejects a successful HTTP response missing wrapped material",
  async (operation) => {
    const fetchImpl = vi.fn(async () => Response.json({}));
    const transport = createAzureKeyVaultKeysHttpsTransport({
      bearerToken: "generated context",
      fetchImpl,
    });
    await expect(invoke(transport, operation)).rejects.toMatchObject({
      code: "provider_denied",
    });
  },
);
it.each(operations)(
  "%s rejects an unversioned or secret endpoint before HTTP",
  async (operation) => {
    const fetchImpl = vi.fn(async () => Response.json({}));
    const transport = createAzureKeyVaultKeysHttpsTransport({
      bearerToken: "generated context",
      fetchImpl,
    });
    for (const keyId of [
      "https://generated.vault.azure.net/keys/generated-root",
      "https://generated.vault.azure.net/secrets/generated/1",
    ]) {
      await expect(invoke(transport, operation, keyId)).rejects.toBeInstanceOf(
        ProtectionError,
      );
    }
    expect(fetchImpl).not.toHaveBeenCalled();
  },
);

it("the real local capsule refuses an HTTP unwrap of the wrong wrapping-secret size", async () => {
  const port = await localRsaPort();
  const protector = createAzureKeyVaultKeysProtector({
    transport: port.transport,
    authorization: "authorized",
  });
  const rootKey = mintWrappingSecret();
  try {
    const wrapped = await protector.wrap({
      context: CONTEXT,
      rootKey,
      versionedKeyId: KEY_ID,
      connectionId: "generated-connection",
      connectionConfigVersion: "1",
      tenantId: "generated-tenant",
    });
    const fetchImpl = vi.fn(async () =>
      Response.json({ value: bytesToB64(new Uint8Array(31)) }),
    );
    const wrongSize = createAzureKeyVaultKeysProtector({
      authorization: "authorized",
      transport: createAzureKeyVaultKeysHttpsTransport({
        bearerToken: "generated context",
        fetchImpl,
      }),
    });
    await expect(
      wrongSize.unwrap({ context: CONTEXT, record: wrapped.record }),
    ).rejects.toMatchObject({ code: "invalid_key_length" });
  } finally {
    rootKey.fill(0);
  }
});
