import { describe, expect, it } from "vitest";
import { ProtectionError } from "../errors.js";
import { GCP_TOKEN_ENDPOINT, mintGcpAccessToken } from "./gcp-oauth.js";

/** PEM armor around a key generated by the test itself — never a real key. */
function armor(label: string, body: string): string {
  return `-----BEGIN ${label}-----\n${body}\n-----END ${label}-----\n`;
}

function pem(pkcs8: ArrayBuffer): string {
  const body = btoa(String.fromCharCode(...new Uint8Array(pkcs8)));
  return armor("PRIVATE KEY", body.match(/.{1,64}/g)?.join("\n") ?? "");
}

type ExtraFields = { token_uri?: string };

async function serviceAccount(extra: ExtraFields = {}) {
  const pair = await crypto.subtle.generateKey(
    {
      name: "RSASSA-PKCS1-v1_5",
      modulusLength: 2048,
      publicExponent: new Uint8Array([1, 0, 1]),
      hash: "SHA-256",
    },
    true,
    ["sign", "verify"],
  );
  const pkcs8 = await crypto.subtle.exportKey("pkcs8", pair.privateKey);
  return {
    publicKey: pair.publicKey,
    json: JSON.stringify({
      type: "service_account",
      client_email: "vault@p1.iam.gserviceaccount.com",
      private_key_id: "kid-1",
      private_key: pem(pkcs8),
      ...extra,
    }),
  };
}

function fromB64Url(value: string): Uint8Array {
  const padded = value.replace(/-/g, "+").replace(/_/g, "/");
  return Uint8Array.from(atob(padded), (c) => c.charCodeAt(0));
}

describe("mintGcpAccessToken", () => {
  it("signs an RS256 assertion the public key verifies and posts it to the fixed endpoint", async () => {
    const { json, publicKey } = await serviceAccount({
      token_uri: "https://attacker.example/token",
    });
    const calls: { url: string; body: string }[] = [];
    const token = await mintGcpAccessToken({
      serviceAccountJson: json,
      now: () => 1_700_000_000_000,
      fetchImpl: async (url, init) => {
        calls.push({ url: String(url), body: String(init?.body) });
        return new Response(JSON.stringify({ access_token: "ya29.token" }), {
          status: 200,
        });
      },
    });
    expect(token).toBe("ya29.token");
    expect(calls).toHaveLength(1);
    expect(calls[0]?.url).toBe(GCP_TOKEN_ENDPOINT);

    const form = new URLSearchParams(calls[0]?.body);
    expect(form.get("grant_type")).toBe(
      "urn:ietf:params:oauth:grant-type:jwt-bearer",
    );
    const [header, claims, signature] = (form.get("assertion") ?? "").split(
      ".",
    );
    if (!header || !claims || !signature)
      throw new Error("malformed assertion");
    expect(JSON.parse(new TextDecoder().decode(fromB64Url(header)))).toEqual({
      alg: "RS256",
      typ: "JWT",
      kid: "kid-1",
    });
    expect(JSON.parse(new TextDecoder().decode(fromB64Url(claims)))).toEqual({
      iss: "vault@p1.iam.gserviceaccount.com",
      scope: "https://www.googleapis.com/auth/cloudkms",
      aud: GCP_TOKEN_ENDPOINT,
      iat: 1_700_000_000,
      exp: 1_700_003_600,
    });
    const valid = await crypto.subtle.verify(
      "RSASSA-PKCS1-v1_5",
      publicKey,
      fromB64Url(signature),
      new TextEncoder().encode(`${header}.${claims}`),
    );
    expect(valid).toBe(true);
  });

  it("refuses a credential without a private key, a bad key, and a refusal from Google", async () => {
    await expect(
      mintGcpAccessToken({
        serviceAccountJson: JSON.stringify({ client_email: "a@b" }),
        fetchImpl: async () => new Response("{}"),
      }),
    ).rejects.toMatchObject({ code: "malformed_encoding" });
    await expect(
      mintGcpAccessToken({
        serviceAccountJson: JSON.stringify({
          client_email: "a@b",
          private_key: armor("PRIVATE KEY", "AAAA"),
        }),
        fetchImpl: async () => new Response("{}"),
      }),
    ).rejects.toMatchObject({ code: "malformed_encoding" });
    const { json } = await serviceAccount();
    await expect(
      mintGcpAccessToken({
        serviceAccountJson: json,
        fetchImpl: async () => new Response("{}", { status: 400 }),
      }),
    ).rejects.toMatchObject({ code: "provider_denied" });
    await expect(
      mintGcpAccessToken({
        serviceAccountJson: json,
        fetchImpl: async () => {
          throw new TypeError("blocked");
        },
      }),
    ).rejects.toBeInstanceOf(ProtectionError);
  });
});
