import {
  AUTH_CEREMONY,
  HUMAN_CEREMONY,
  NEVER_AGENT_SECRET,
  OPS_PLANE,
  PAGES_HAS_NO_HOST,
  PM_PLANE,
} from "./exclusions.js";
import type { Capability } from "./index.js";

/**
 * The native host: one `opensesame` binary that runs the Host API, the local
 * agent daemon and the workload connector host as subcommands, and answers as
 * each credential helper and browser bridge under its link name (ADR 0138).
 */
export const nativeHostCapabilities: readonly Capability[] = [
  {
    id: "daemon.status",
    title: "Local host agent status",
    plane: "host",
    kind: "read",
    surfaces: {
      cli: "opensesame daemon status",
      pwa: null,
      mcp_host: "daemon_health",
      mcp_client: null,
      webmcp: null,
    },
    excluded: { pwa: PAGES_HAS_NO_HOST, webmcp: PAGES_HAS_NO_HOST },
  },
  {
    id: "daemon.lifecycle",
    title: "Install/start/stop the local host agent",
    plane: "host",
    kind: "admin",
    surfaces: {
      cli: "opensesame daemon install",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: { mcp_host: OPS_PLANE, mcp_client: OPS_PLANE },
  },
  {
    id: "daemon.serve",
    title: "Run the local host agent in this process",
    plane: "host",
    kind: "admin",
    surfaces: {
      cli: "opensesame daemon run",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: { mcp_host: OPS_PLANE, mcp_client: OPS_PLANE },
  },
  {
    id: "daemon.approvals",
    title: "Approve a device code or claim through the local host agent",
    plane: "host",
    kind: "ceremony",
    surfaces: {
      cli: "opensesame daemon approve-device",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: { mcp_host: HUMAN_CEREMONY, mcp_client: HUMAN_CEREMONY },
  },
  {
    id: "host.serve",
    title: "Run the Host API",
    plane: "host",
    kind: "admin",
    surfaces: {
      cli: "opensesame host run",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: { mcp_host: OPS_PLANE, mcp_client: OPS_PLANE },
  },
  {
    id: "worker.serve",
    title: "Run the workload connector host",
    plane: "host",
    kind: "admin",
    surfaces: {
      cli: "opensesame worker run",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: { mcp_host: OPS_PLANE, mcp_client: OPS_PLANE },
  },
  {
    id: "helpers.link",
    title: "Link the credential helpers and browser bridges to this binary",
    plane: "host",
    kind: "admin",
    surfaces: {
      cli: "opensesame helpers link",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: { mcp_host: OPS_PLANE, mcp_client: OPS_PLANE },
  },

  {
    id: "host.auth.doctor",
    title: "Diagnose the local sign-in state",
    plane: "host",
    kind: "read",
    surfaces: {
      cli: "opensesame auth doctor",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: { mcp_host: OPS_PLANE, mcp_client: OPS_PLANE },
  },
  {
    id: "leases.acquire",
    title: "Acquire or revoke a short-lived credential lease",
    plane: "host",
    kind: "act",
    surfaces: {
      cli: "opensesame lease",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: {
      mcp_host: NEVER_AGENT_SECRET,
      mcp_client: NEVER_AGENT_SECRET,
      webmcp: NEVER_AGENT_SECRET,
    },
  },
  {
    id: "connections.import",
    title: "Import non-secret connection configuration",
    plane: "host",
    kind: "admin",
    surfaces: {
      cli: "opensesame import",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: { mcp_host: OPS_PLANE, mcp_client: OPS_PLANE },
  },
  {
    id: "files.crypto",
    title: "Encrypt or decrypt a file without plaintext in argv or stdout",
    plane: "client_local",
    kind: "act",
    surfaces: {
      cli: "opensesame crypto",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
  },
  {
    id: "config_files.print",
    title: "Print the native project configuration files",
    plane: "client_local",
    kind: "read",
    surfaces: {
      cli: "opensesame config-files",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
  },
  {
    id: "env_spec.init",
    title: "Start a project's .env.schema",
    plane: "client_local",
    kind: "admin",
    surfaces: {
      cli: "opensesame init",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
  },
  {
    id: "env_spec.dev",
    title: "Resolve and run a project's environment",
    plane: "client_local",
    kind: "act",
    surfaces: {
      cli: "opensesame dev",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
  },
  {
    id: "pm_bridges.install",
    title: "Install a password-manager bridge for a browser",
    plane: "client_local",
    kind: "admin",
    surfaces: {
      cli: "opensesame bridge install",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: { webmcp: PM_PLANE },
  },
  {
    id: "sync.cursor.read",
    title: "Read this device's sync cursor",
    plane: "client_local",
    kind: "read",
    surfaces: {
      cli: null,
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
      extension: "message:opensesame.sync_cursor",
    },
  },
];
