import { NEVER_AGENT_SECRET } from "./exclusions.js";
import {
  HANDOFF,
  NATIVE_ONLY,
  NO_CUSTODY,
  WALLET_ONLY,
} from "./password-workflows.js";
import type { Capability } from "./types.js";

/** Operations with no browser-store equivalent are explicitly native-only. */
export const passwordProviderCapabilities: readonly Capability[] = [
  {
    id: "password_provider.native_cli",
    title: "Native password-provider command family",
    plane: "client_local",
    kind: "ceremony",
    surfaces: {
      cli: "opensesame password-agent",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: {
      pwa: NATIVE_ONLY,
      mcp_host: NEVER_AGENT_SECRET,
      mcp_client: NEVER_AGENT_SECRET,
      webmcp: NEVER_AGENT_SECRET,
      extension: NATIVE_ONLY,
      android: WALLET_ONLY,
    },
  },
  {
    id: "password_provider.read",
    title: "Read a credential value on the human plane",
    plane: "client_local",
    kind: "ceremony",
    surfaces: {
      cli: "opensesame-id read",
      pwa: "lib/vault/password-workflows.ts:resolveLocalReference",
      mcp_host: null,
      mcp_client: null,
      webmcp: "opensesame_open_password_workflow",
    },
    excluded: {
      mcp_host: NEVER_AGENT_SECRET,
      mcp_client: NEVER_AGENT_SECRET,
      extension: HANDOFF,
      android: WALLET_ONLY,
    },
  },
  {
    id: "password_provider.run",
    title: "Execute a local child with provider-injected environment",
    plane: "client_local",
    kind: "ceremony",
    surfaces: {
      cli: "opensesame-id run",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: {
      pwa: NATIVE_ONLY,
      mcp_host: NEVER_AGENT_SECRET,
      mcp_client: NEVER_AGENT_SECRET,
      webmcp: NEVER_AGENT_SECRET,
      extension: NATIVE_ONLY,
      android: WALLET_ONLY,
    },
  },
  {
    id: "password_provider.env_resolve",
    title: "Write a private file with resolved credential values",
    plane: "client_local",
    kind: "ceremony",
    surfaces: {
      cli: "opensesame-id env resolve",
      pwa: "lib/vault/password-workflows.ts:resolveLocalEnvTemplate",
      mcp_host: null,
      mcp_client: null,
      webmcp: "opensesame_open_password_workflow",
    },
    excluded: {
      mcp_host: NEVER_AGENT_SECRET,
      mcp_client: NEVER_AGENT_SECRET,
      extension: HANDOFF,
      android: WALLET_ONLY,
    },
  },
  {
    id: "password_provider.env_run",
    title: "Run a local child from a reference template",
    plane: "client_local",
    kind: "ceremony",
    surfaces: {
      cli: "opensesame-id env run",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: {
      pwa: NATIVE_ONLY,
      mcp_host: NEVER_AGENT_SECRET,
      mcp_client: NEVER_AGENT_SECRET,
      webmcp: NEVER_AGENT_SECRET,
      extension: NATIVE_ONLY,
      android: WALLET_ONLY,
    },
  },
  {
    id: "password_provider.doctor",
    title: "Check native provider dependencies and authentication posture",
    plane: "client_local",
    kind: "read",
    surfaces: {
      cli: "opensesame-id doctor",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: {
      pwa: NATIVE_ONLY,
      mcp_host: NO_CUSTODY,
      mcp_client: NO_CUSTODY,
      webmcp: NATIVE_ONLY,
      extension: NATIVE_ONLY,
      android: WALLET_ONLY,
    },
  },
  {
    id: "password_provider.account_connect",
    title: "Connect a privately supplied provider service account",
    plane: "client_local",
    kind: "ceremony",
    surfaces: {
      cli: "opensesame-id service-account connect",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: {
      pwa: NATIVE_ONLY,
      mcp_host: NEVER_AGENT_SECRET,
      mcp_client: NEVER_AGENT_SECRET,
      webmcp: NEVER_AGENT_SECRET,
      extension: NATIVE_ONLY,
      android: WALLET_ONLY,
    },
  },
  {
    id: "password_provider.account_setup",
    title: "Provision a scoped provider service account",
    plane: "client_local",
    kind: "ceremony",
    surfaces: {
      cli: "opensesame-id service-account setup",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: {
      pwa: NATIVE_ONLY,
      mcp_host: NEVER_AGENT_SECRET,
      mcp_client: NEVER_AGENT_SECRET,
      webmcp: NEVER_AGENT_SECRET,
      extension: NATIVE_ONLY,
      android: WALLET_ONLY,
    },
  },
  {
    id: "password_provider.account_status",
    title: "Inspect saved provider service-account configuration",
    plane: "client_local",
    kind: "read",
    surfaces: {
      cli: "opensesame-id service-account status",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: {
      pwa: NATIVE_ONLY,
      mcp_host: NO_CUSTODY,
      mcp_client: NO_CUSTODY,
      webmcp: NATIVE_ONLY,
      extension: NATIVE_ONLY,
      android: WALLET_ONLY,
    },
  },
  {
    id: "password_provider.account_recover",
    title: "Recover a provider account into OS credential custody",
    plane: "client_local",
    kind: "ceremony",
    surfaces: {
      cli: "opensesame-id service-account recover",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: {
      pwa: NATIVE_ONLY,
      mcp_host: NEVER_AGENT_SECRET,
      mcp_client: NEVER_AGENT_SECRET,
      webmcp: NEVER_AGENT_SECRET,
      extension: NATIVE_ONLY,
      android: WALLET_ONLY,
    },
  },
  {
    id: "password_provider.account_forget",
    title: "Remove locally saved provider authentication",
    plane: "client_local",
    kind: "ceremony",
    surfaces: {
      cli: "opensesame-id service-account forget",
      pwa: null,
      mcp_host: null,
      mcp_client: null,
      webmcp: null,
    },
    excluded: {
      pwa: NATIVE_ONLY,
      mcp_host: NEVER_AGENT_SECRET,
      mcp_client: NEVER_AGENT_SECRET,
      webmcp: NEVER_AGENT_SECRET,
      extension: NATIVE_ONLY,
      android: WALLET_ONLY,
    },
  },
];
