import { createItem } from "@opensesame/vault-core";
import { afterEach, expect, it, vi } from "vitest";
import { configureHost } from "../../../host.js";
import { createMemoryStorage } from "../../../memory-storage.js";
import { createTestHost } from "../../../test-host.js";
import { webLocksDouble } from "../../__tests__/web-locks-double.js";
import type { VaultStore } from "../../vault/store.js";
import { makeOpfs } from "../wipe/fake-opfs.test-support.js";

const PASSWORD = "generated scratch owner password";
const PIN = "48291037";
const SCRATCH = "guest-scratch";
let store: VaultStore | undefined;

afterEach(async () => {
  try {
    store?.lock();
    const files = await import("../../vfs.js");
    await files.vfsFlush();
    const realm = await import("../../decoy-session.js");
    if (store && realm.requiresFreshOwnerAuthentication()) {
      store.rehydrate();
      await store.unlock(PASSWORD);
      expect(realm.requiresFreshOwnerAuthentication()).toBe(false);
      store.lock();
      await files.vfsFlush();
    }
    const kv = await import("../../kv.js");
    await kv.kvFlush();
  } finally {
    store = undefined;
    vi.restoreAllMocks();
    vi.unstubAllGlobals();
    configureHost(createTestHost());
  }
});

async function fixture() {
  vi.resetModules();
  const root = makeOpfs();
  vi.stubGlobal("navigator", {
    storage: { getDirectory: async () => root },
    locks: webLocksDouble(),
  });
  configureHost(
    createTestHost({
      storage: { local: createMemoryStorage(), session: createMemoryStorage() },
    }),
  );
  const kv = await import("../../kv.js");
  const files = await import("../../vfs.js");
  const realm = await import("../../decoy-session.js");
  const { writeLastVaultId } = await import("../../last-vault.js");
  const { VaultStore } = await import("../../vault/store.js");
  await kv.kvHydrate([]);
  expect(kv.kvDurability()).toBe("persistent");
  const owner = new VaultStore();
  store = owner;
  await owner.create(PASSWORD);
  await owner.saveItem(createItem("note", "Original owner data"));
  owner.lock();
  await files.vfsFlush();
  await owner.createGuest();
  await owner.enrollPin(PIN);
  await owner.saveItem(createItem("note", "Sealed guest data"));
  await owner.protection.ensureProtectionProjected();
  expect(owner.getSnapshot().header?.protection?.authB64).toBeTruthy();
  owner.lock();
  await files.vfsFlush();
  writeLastVaultId(files.PERSONAL_TOMB);
  owner.rehydrate();
  await owner.unlock(PASSWORD);
  owner.lock();
  await files.vfsFlush();
  const attempts = "vault.attempts.v1.guest";
  await kv.kvSetDurable(attempts, JSON.stringify({ fails: 2, until: 0 }));
  const protectedKeys = [
    ...[files.PERSONAL_TOMB, files.GUEST_TOMB].flatMap((tomb) =>
      [files.HEADER_PATH, files.BODY_PATH].map((path) =>
        files.tombFileKey(tomb, path),
      ),
    ),
    attempts,
  ];
  const protectedData = protectedKeys.map((key) => kv.kvGet(key));
  return { root, owner, kv, files, realm, protectedKeys, protectedData };
}

it("removes persisted orphan scratch headers on cold replay while preserving owner and sealed guest data", async () => {
  const f = await fixture();
  await f.owner.createGuest({ decoy: true, isolated: true, resume: false });
  await f.owner.saveItem(createItem("note", "Previous synthetic data"));
  const headerKey = f.files.tombFileKey(SCRATCH, f.files.HEADER_PATH);
  const bodyKey = f.files.tombFileKey(SCRATCH, f.files.BODY_PATH);
  const header = f.kv.kvGet(headerKey);
  const body = f.kv.kvGet(bodyKey);
  if (!header || !body)
    throw new Error("Expected generated encrypted scratch.");
  f.owner.lock();
  await f.files.vfsFlush();
  await f.kv.kvRefresh(headerKey, 1024 * 1024);
  await f.kv.kvRefresh(bodyKey, 1024 * 1024);
  expect(f.kv.kvGet(headerKey)).toBeNull();
  expect(f.kv.kvGet(bodyKey)).toBeNull();
  // A previous version left these genuinely generated bytes off the registry.
  await f.kv.kvSetDurable(headerKey, header);
  await f.kv.kvSetDurable(bodyKey, body);
  expect(f.files.listTombs()).not.toContain(SCRATCH);
  vi.resetModules();
  const kv = await import("../../kv.js");
  const files = await import("../../vfs.js");
  const realm = await import("../../decoy-session.js");
  const { tombStorageKeys } = await import("../../vault/tomb-migration.js");
  await kv.kvHydrate([files.TOMBS_REGISTRY_KEY, ...f.protectedKeys]);
  await kv.kvHydrate(files.listTombs().flatMap(tombStorageKeys));
  expect(kv.kvGet(headerKey)).toBeNull();
  expect(realm.requiresFreshOwnerAuthentication()).toBe(true);
  const { VaultStore } = await import("../../vault/store.js");
  const replay = new VaultStore();
  store = replay;
  await replay.createGuest({ decoy: true, isolated: true, resume: false });
  await replay.saveItem(createItem("note", "New synthetic data"));
  expect(replay.getSnapshot().items.map((item) => item.name)).toEqual([
    "New synthetic data",
  ]);
  replay.lock();
  await files.vfsFlush();
  await kv.kvRefresh(headerKey, 1024 * 1024);
  await kv.kvRefresh(bodyKey, 1024 * 1024);
  expect(kv.kvGet(headerKey)).toBeNull();
  expect(kv.kvGet(bodyKey)).toBeNull();
  expect(f.protectedKeys.map((key) => kv.kvGet(key))).toEqual(f.protectedData);
  expect(realm.requiresFreshOwnerAuthentication()).toBe(true);
  await expect(
    replay.unlock("wrong generated owner password"),
  ).rejects.toThrow();
  expect(realm.requiresFreshOwnerAuthentication()).toBe(true);
  await replay.unlock(PASSWORD);
  expect(realm.requiresFreshOwnerAuthentication()).toBe(false);
  expect(replay.getSnapshot().items.map((item) => item.name)).toEqual([
    "Original owner data",
  ]);
  replay.lock();
  replay.prepareGuestUnlock();
  await replay.unlockWithPin(PIN);
  expect(replay.getSnapshot().items.map((item) => item.name)).toEqual([
    "Sealed guest data",
  ]);
});

it("drains an older queued lock cleanup before admitting and persisting its synthetic successor", async () => {
  const f = await fixture();
  await f.owner.createGuest({ decoy: true, isolated: true, resume: false });
  await f.owner.saveItem(createItem("note", "Older synthetic data"));
  const bodyKey = f.files.tombFileKey(SCRATCH, f.files.BODY_PATH);
  let reached = () => {};
  let release = () => {};
  const started = new Promise<void>((resolve) => {
    reached = resolve;
  });
  const blocked = new Promise<void>((resolve) => {
    release = resolve;
  });
  const original = f.files.vfsSeams.deleteRaw;
  let held = false;
  vi.spyOn(f.files.vfsSeams, "deleteRaw").mockImplementation(async (key) => {
    if (key === bodyKey && !held) {
      held = true;
      reached();
      await blocked;
    }
    await original(key);
  });
  f.owner.lock();
  await started;
  const successor = f.owner.createGuest({
    decoy: true,
    isolated: true,
    resume: false,
  });
  try {
    expect(f.owner.getSnapshot().status).not.toBe("unlocked");
  } finally {
    release();
  }
  await successor;
  await f.owner.saveItem(createItem("note", "Successor synthetic data"));
  await f.files.vfsFlush();
  const durable = f.kv.kvGet(bodyKey);
  await f.kv.kvRefresh(bodyKey, 1024 * 1024);
  expect(durable).not.toBeNull();
  expect(f.kv.kvGet(bodyKey)).toBe(durable);
  expect(
    f.kv.kvGet(f.files.tombFileKey(SCRATCH, f.files.HEADER_PATH)),
  ).not.toBeNull();
  expect(f.owner.getSnapshot().items.map((item) => item.name)).toEqual([
    "Successor synthetic data",
  ]);
  expect(f.protectedKeys.map((key) => f.kv.kvGet(key))).toEqual(
    f.protectedData,
  );
  expect(f.realm.requiresFreshOwnerAuthentication()).toBe(true);
});

it("does not admit a scratch key when its public lock cancels an awaited cleanup", async () => {
  const f = await fixture();
  const bodyKey = f.files.tombFileKey(SCRATCH, f.files.BODY_PATH);
  let reached = () => {};
  let release = () => {};
  const started = new Promise<void>((resolve) => {
    reached = resolve;
  });
  const blocked = new Promise<void>((resolve) => {
    release = resolve;
  });
  const original = f.files.vfsSeams.deleteRaw;
  vi.spyOn(f.files.vfsSeams, "deleteRaw").mockImplementation(async (key) => {
    await original(key);
    if (key === bodyKey) {
      reached();
      await blocked;
    }
  });
  const opening = f.owner.createGuest({
    decoy: true,
    isolated: true,
    resume: false,
  });
  const refused = expect(opening).rejects.toThrow(/session changed/);
  await started;
  try {
    f.owner.lock();
  } finally {
    release();
  }
  await refused;
  expect(f.owner.getSnapshot().status).toBe("locked");
  expect(f.files.tombUnlocked(SCRATCH)).toBe(false);
  expect(f.protectedKeys.map((key) => f.kv.kvGet(key))).toEqual(
    f.protectedData,
  );
  expect(f.realm.requiresFreshOwnerAuthentication()).toBe(true);
  await f.owner.unlock(PASSWORD);
  expect(f.realm.requiresFreshOwnerAuthentication()).toBe(false);
});
