import { useEffect, useState } from "react";
import { Link } from "react-router";
/**
 * Drop ceremonies (docs/design/secret-drop.md §3/§4/§5).
 *
 * - `ShareSecretDrop`: the share ceremony on an existing vault secret — TTL,
 *   *Keep a copy* (default on; it governs only the drop record — the secret
 *   item itself is never modified), seal + create, drop card.
 * - `NewDropCeremony`: the +new → Drop flow — text or a file, TTL, *Keep a
 *   copy* (default off). The payload never enters the vault body unless kept.
 * - `DropRecordFields`: the drop record's detail — state, countdown, the
 *   kept copy if there is one — and the disposal poll that purges the record
 *   once nothing can open the drop again.
 *
 * In every flow the plaintext is never shown again after sealing: the drop
 * card carries only the link, the user code, the QR, and the expiry.
 */

import {
  ConcealedValue,
  CopyButton,
  FieldRow,
  RevealButton,
  useCopyFeedback,
} from "../../components/FieldRow.js";
import {
  IconCheck,
  IconChevronLeft,
  IconDrop,
  IconX,
} from "../../components/Icons.js";
import { QrCode } from "../../components/QrCode.js";
import { b64ToBytes } from "../../lib/vault/crypto.js";
import {
  type CreatedDrop,
  type DropPayload,
  createDrop,
  sweepDrop,
} from "../../lib/vault/drop.js";
import { useVaultStore } from "../../lib/vault/hooks.js";
import type { DropItem, SecretItem } from "../../lib/vault/model.js";
import { generatePassphrase } from "../../lib/vault/password.js";

export const DROP_TTL_OPTIONS = [
  { label: "10 minutes", ms: 600_000 },
  { label: "1 hour", ms: 3_600_000 },
  { label: "1 day", ms: 86_400_000 },
] as const;

/** Autogenerated drop names — memorable defaults, never required. */
function suggestDropName(): string {
  return generatePassphrase({
    mode: "passphrase",
    words: 3,
    separator: "-",
    capitalize: false,
    includeNumber: false,
  });
}

export function formatExpiry(iso: string): string {
  return new Date(iso).toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

/** What a finished ceremony shows: link, code, QR, expiry — never the payload. */
export function DropCard({ drop }: { drop: CreatedDrop }) {
  const { copied, failed, copy } = useCopyFeedback();
  return (
    <section className="detail__group" aria-label="Drop ready">
      <h2 className="detail__grouphead">Drop ready</h2>
      <FieldRow
        label="Link"
        actions={
          <CopyButton
            value={drop.link}
            label="drop link"
            fieldKey="drop-link"
            copied={copied}
            failed={failed}
            onCopy={copy}
          />
        }
      >
        <span className="frow__value frow__value--mono drop-card__link">
          {drop.link}
        </span>
      </FieldRow>
      <FieldRow
        label="User code"
        actions={
          <CopyButton
            value={drop.userCode}
            label="user code"
            fieldKey="drop-code"
            copied={copied}
            failed={failed}
            onCopy={copy}
          />
        }
      >
        <span className="frow__value frow__value--mono">{drop.userCode}</span>
      </FieldRow>
      <div className="drop-card__qr">
        <QrCode
          value={drop.link}
          label="Scan to open this drop"
          shortcode={drop.userCode}
          size={144}
        />
      </div>
      <p className="hint">Expires {formatExpiry(drop.record.expiresAt)}.</p>
      <p>Whoever opens the link and enters the code sees it once.</p>
    </section>
  );
}

function TtlPicker({
  value,
  onChange,
}: {
  value: number;
  onChange: (ms: number) => void;
}) {
  return (
    <div className="field">
      <label htmlFor="drop-ttl">Opens for</label>
      <select
        id="drop-ttl"
        value={String(value)}
        onChange={(event) => onChange(Number(event.target.value))}
      >
        {DROP_TTL_OPTIONS.map((option) => (
          <option key={option.ms} value={option.ms}>
            {option.label}
          </option>
        ))}
      </select>
    </div>
  );
}

/** Share ceremony on an existing vault secret. The secret item is untouched. */
export function ShareSecretDrop({
  item,
  initialOpen = false,
}: {
  item: SecretItem;
  initialOpen?: boolean;
}) {
  const store = useVaultStore();
  const [open, setOpen] = useState(initialOpen);
  const [ttlMs, setTtlMs] = useState<number>(DROP_TTL_OPTIONS[1].ms);
  // Sharing an existing vault secret defaults to keeping a copy — the secret
  // stays in the vault either way; this governs only the drop record.
  const [keepCopy, setKeepCopy] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [drop, setDrop] = useState<CreatedDrop | null>(null);

  async function share() {
    setBusy(true);
    setError(null);
    try {
      const name = item.name || "Shared secret";
      const created = await createDrop({
        name,
        payload: { kind: "text", name, text: item.value },
        ttlMs,
        keepCopy,
      });
      await store.saveItem(created.record);
      setDrop(created);
    } catch (caught) {
      setError(
        caught instanceof Error
          ? caught.message
          : "The drop could not be created.",
      );
    } finally {
      setBusy(false);
    }
  }

  if (drop) {
    return (
      <section className="detail__group">
        <DropCard drop={drop} />
        <div className="actions">
          <Link className="btn btn--sm" to={`/vault/${drop.record.id}`}>
            Open the drop record
          </Link>
        </div>
      </section>
    );
  }

  if (!open) {
    return (
      <button
        type="button"
        className="btn btn--sm"
        onClick={() => setOpen(true)}
      >
        <IconDrop size={15} />
        Share once
      </button>
    );
  }

  return (
    <section className="detail__group" aria-label="Share this secret once">
      <h2 className="detail__grouphead">Share this secret once</h2>
      <p className="hint">
        Sealed here with a fresh key; the server only ever sees ciphertext.
      </p>
      <TtlPicker value={ttlMs} onChange={setTtlMs} />
      <div className="field">
        <label className="check">
          <input
            type="checkbox"
            checked={keepCopy}
            onChange={(event) => setKeepCopy(event.target.checked)}
          />
          <span>Keep a copy on the drop record</span>
        </label>
      </div>
      {error ? (
        <p className="note note--err" role="alert">
          <span>{error}</span>
        </p>
      ) : null}
      <div className="actions">
        <button
          type="button"
          className="btn btn--primary btn--sm"
          disabled={busy}
          aria-busy={busy}
          onClick={() => void share()}
        >
          {busy ? "Sealing…" : "Seal and share"}
        </button>
        <button
          type="button"
          className="btn btn--ghost btn--sm"
          disabled={busy}
          onClick={() => setOpen(false)}
        >
          Cancel
        </button>
      </div>
    </section>
  );
}

/** The +new → Drop flow: a burner share whose payload never has to be vaulted. */
export function NewDropCeremony() {
  const store = useVaultStore();
  // The name is autogenerated by default; typing overrides it, and leaving
  // the field untouched (or clearing it) falls back to the suggestion.
  const [suggested] = useState(() => suggestDropName());
  const [name, setName] = useState("");
  const [source, setSource] = useState<"text" | "file">("text");
  const [text, setText] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const [ttlMs, setTtlMs] = useState<number>(DROP_TTL_OPTIONS[1].ms);
  // A burner starts with nothing kept: the payload never enters the vault
  // body unless the user explicitly asks for a copy.
  const [keepCopy, setKeepCopy] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [drop, setDrop] = useState<CreatedDrop | null>(null);

  async function submit() {
    const trimmed = name.trim();
    setBusy(true);
    setError(null);
    try {
      let payload: DropPayload;
      let dropName = trimmed;
      if (source === "text") {
        if (!text) throw new Error("Enter the text to drop.");
        if (!dropName) dropName = suggested;
        payload = { kind: "text", name: dropName, text };
      } else {
        if (!file) throw new Error("Choose a file to drop.");
        if (!dropName) dropName = file.name || suggested;
        payload = {
          kind: "file",
          name: dropName,
          contentType: file.type || "application/octet-stream",
          bytes: new Uint8Array(await file.arrayBuffer()),
        };
      }
      const created = await createDrop({
        name: dropName,
        payload,
        ttlMs,
        keepCopy,
      });
      await store.saveItem(created.record);
      setDrop(created);
    } catch (caught) {
      setError(
        caught instanceof Error
          ? caught.message
          : "The drop could not be created.",
      );
    } finally {
      setBusy(false);
    }
  }

  if (drop) {
    return (
      <div className="detail">
        <div className="detail__heading">
          <h1>Drop created</h1>
        </div>
        <DropCard drop={drop} />
        <div className="actions">
          <Link
            className="btn btn--primary btn--sm"
            to={`/vault/${drop.record.id}`}
          >
            Open the drop record
          </Link>
          <Link className="btn btn--sm" to="/vault">
            Back to the vault
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="detail">
      <form
        className="editor"
        onSubmit={(event) => {
          event.preventDefault();
          void submit();
        }}
      >
        <div className="editor__titlerow">
          <Link
            className="icon-btn editor__backbtn"
            aria-label="Back"
            title="Back"
            to="/vault"
          >
            <IconChevronLeft size={17} />
          </Link>
          <input
            className="editor__name"
            aria-label="Name"
            value={name}
            placeholder={
              source === "file" ? "Defaults to the file name" : suggested
            }
            onChange={(event) => setName(event.target.value)}
          />
          <span className="editor__ext" aria-hidden="true">
            .drop
          </span>
          <button
            type="submit"
            className="icon-btn editor__save"
            disabled={busy}
            aria-busy={busy}
            aria-label={busy ? "Sealing…" : "Seal and create drop"}
            title={busy ? "Sealing…" : "Seal and create drop"}
          >
            <IconCheck size={17} />
          </button>
          <Link className="icon-btn" aria-label="Cancel" title="Cancel" to="/vault">
            <IconX size={17} />
          </Link>
        </div>
        <p className="hint editor__seal">
          A one-time share: sealed here, opened once, then gone. The payload is
          not stored in this vault unless you keep a copy.
        </p>

        <div className="field">
          <span className="label">Payload</span>
          <fieldset className="sites-effect-toggle" aria-label="Payload source">
            <button
              type="button"
              className={
                source === "text"
                  ? "sites-effect is-on is-allow"
                  : "sites-effect"
              }
              onClick={() => setSource("text")}
            >
              Text
            </button>
            <button
              type="button"
              className={
                source === "file"
                  ? "sites-effect is-on is-allow"
                  : "sites-effect"
              }
              onClick={() => setSource("file")}
            >
              File
            </button>
          </fieldset>
          {source === "text" ? (
            <textarea
              id="drop-text"
              aria-label="Text to drop"
              rows={5}
              value={text}
              onChange={(event) => setText(event.target.value)}
            />
          ) : (
            <input
              id="drop-file"
              aria-label="File to drop"
              type="file"
              onChange={(event) => setFile(event.target.files?.[0] ?? null)}
            />
          )}
          <p className="hint">Up to 1 MiB once encrypted.</p>
        </div>

        <TtlPicker value={ttlMs} onChange={setTtlMs} />

        <div className="field">
          <label className="check">
            <input
              type="checkbox"
              checked={keepCopy}
              onChange={(event) => setKeepCopy(event.target.checked)}
            />
            <span>Keep a copy on the drop record</span>
          </label>
        </div>

        {error ? (
          <p className="note note--err" role="alert">
            <span>{error}</span>
          </p>
        ) : null}

      </form>
    </div>
  );
}

function formatRemaining(ms: number): string {
  const totalSeconds = Math.max(0, Math.floor(ms / 1000));
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;
  if (hours > 0) return `${hours}h ${minutes}m left`;
  if (minutes > 0) return `${minutes}m ${seconds}s left`;
  return `${seconds}s left`;
}

function downloadKeptFile(copy: {
  name: string;
  contentType: string;
  dataB64: string;
}): void {
  const bytes = b64ToBytes(copy.dataB64);
  // SAFETY: Blob accepts a typed array view; bytes is a fresh local buffer.
  const blob = new Blob([bytes], { type: copy.contentType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = copy.name;
  anchor.click();
  URL.revokeObjectURL(url);
}

/** Drop record detail: state, countdown, optional kept copy, disposal poll. */
export function DropRecordFields({ item }: { item: DropItem }) {
  const store = useVaultStore();
  const [now, setNow] = useState(() => Date.now());
  const [revealed, setRevealed] = useState(false);
  const { copied, failed, copy } = useCopyFeedback();
  const kept = item.keptCopy;

  // Disposal: poll once per viewing; a terminal claim purges the record, and
  // so does the TTL lapsing while this page is open.
  useEffect(() => {
    void sweepDrop(item, () => store.purgeItem(item.id));
  }, [item, store]);

  useEffect(() => {
    const timer = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(timer);
  }, []);

  const remaining = Date.parse(item.expiresAt) - now;
  const stateLabel =
    item.state === "pending"
      ? "Waiting to be opened"
      : item.state === "consumed"
        ? "Opened"
        : "Expired";

  return (
    <>
      <section className="detail__group">
        <h2 className="detail__grouphead">Drop</h2>
        <FieldRow label="State">
          <span className="frow__value">{stateLabel}</span>
        </FieldRow>
        <FieldRow label="Opens until">
          <span className="frow__value">
            {formatExpiry(item.expiresAt)}
            {item.state === "pending" && remaining > 0
              ? ` · ${formatRemaining(remaining)}`
              : ""}
          </span>
        </FieldRow>
        <p className="hint">
          This record is purged as soon as the drop is opened or lapses.
        </p>
      </section>

      {kept ? (
        <section className="detail__group">
          <h2 className="detail__grouphead">Kept copy</h2>
          {kept.kind === "text" ? (
            <FieldRow
              label="Text"
              actions={
                <>
                  <RevealButton
                    revealed={revealed}
                    label="kept copy"
                    onToggle={() => setRevealed((value) => !value)}
                  />
                  <CopyButton
                    value={kept.text}
                    label="kept copy"
                    fieldKey="kept-copy"
                    copied={copied}
                    failed={failed}
                    onCopy={copy}
                  />
                </>
              }
            >
              <ConcealedValue
                value={kept.text}
                label="kept copy"
                revealed={revealed}
              />
            </FieldRow>
          ) : (
            <FieldRow
              label="File"
              actions={
                <button
                  type="button"
                  className="btn btn--sm"
                  onClick={() => downloadKeptFile(kept)}
                >
                  Download
                </button>
              }
            >
              <span className="frow__value">{kept.name}</span>
            </FieldRow>
          )}
        </section>
      ) : null}
    </>
  );
}
