import { useState } from "react";
import { Link } from "react-router";
import {
  type CreatedDrop,
  type DropPayload,
  createDrop,
} from "../../lib/vault/drop.js";
import { useVault, useVaultStore } from "../../lib/vault/hooks.js";
import type { Folder } from "../../lib/vault/model.js";
import { generatePassphrase } from "../../lib/vault/password.js";
import { DropCard } from "./DropCeremony.js";
import { DROP_TTL_OPTIONS, TtlPicker } from "./DropTtl.js";
import { EditorActions } from "./EditorActions.js";
import { EditorTitle } from "./EditorTitle.js";
import { useEditorPath } from "./useEditorPath.js";

/** Autogenerated drop names — memorable defaults, never required. */
function suggestDropName(): string {
  return generatePassphrase({
    mode: "passphrase",
    words: 3,
    separator: "-",
    capitalize: false,
    includeNumber: false,
  });
}
function CreatedDropView({ drop }: { drop: CreatedDrop }) {
  return (
    <div className="detail">
      <div className="detail__heading">
        <h1>Drop created</h1>
      </div>
      <DropCard drop={drop} />
      <div className="actions">
        <Link
          className="btn btn--primary btn--sm"
          to={`/vault/${drop.record.id}`}
        >
          Open the drop record
        </Link>
        <Link className="btn btn--sm" to="/vault">
          Back to the vault
        </Link>
      </div>
    </div>
  );
}

function useNewDrop(initialName: string, initialFolder?: Folder) {
  const store = useVaultStore();
  const { folders } = useVault();
  // The name is autogenerated by default; typing overrides it, and leaving
  // the field untouched (or clearing it) falls back to the suggestion.
  const [suggested] = useState(() => suggestDropName());
  const [name, setName] = useState(initialName);
  const [folderId, setFolderId] = useState<string | null>(
    initialFolder?.id ?? null,
  );
  const [source, setSource] = useState<"text" | "file">("text");
  const [text, setText] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const [ttlMs, setTtlMs] = useState<number>(DROP_TTL_OPTIONS[1].ms);
  // A burner starts with nothing kept: the payload never enters the vault
  // body unless the user explicitly asks for a copy.
  const [keepCopy, setKeepCopy] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [drop, setDrop] = useState<CreatedDrop | null>(null);
  const path = useEditorPath(
    { name, folderId },
    folders,
    (next) => {
      setName(next.name);
      setFolderId(next.folderId);
    },
    setError,
    initialFolder,
  );

  async function submit() {
    setBusy(true);
    setError(null);
    try {
      const location = path.resolve();
      let payload: DropPayload;
      let dropName = location.name.trim();
      if (source === "text") {
        if (!text) throw new Error("Enter the text to drop.");
        if (!dropName) dropName = suggested;
        payload = { kind: "text", name: dropName, text };
      } else {
        if (!file) throw new Error("Choose a file to drop.");
        if (!dropName) dropName = file.name || suggested;
        payload = {
          kind: "file",
          name: dropName,
          contentType: file.type || "application/octet-stream",
          bytes: new Uint8Array(await file.arrayBuffer()),
        };
      }
      const created = await createDrop({
        name: dropName,
        payload,
        ttlMs,
        keepCopy,
      });
      created.record.folderId = location.folderId;
      await store.saveItem(created.record, location.folder);
      setDrop(created);
    } catch (caught) {
      setError(
        caught instanceof Error
          ? caught.message
          : "The drop could not be created.",
      );
    } finally {
      setBusy(false);
    }
  }
  return {
    suggested,
    name,
    setName,
    folderId,
    setFolderId,
    source,
    setSource,
    text,
    setText,
    setFile,
    ttlMs,
    setTtlMs,
    keepCopy,
    setKeepCopy,
    busy,
    error,
    drop,
    path,
    submit,
  };
}

function DropPayloadFields({
  source,
  setSource,
  text,
  setText,
  setFile,
}: Pick<
  ReturnType<typeof useNewDrop>,
  "source" | "setSource" | "text" | "setText" | "setFile"
>) {
  return (
    <div className="field">
      <span className="label">Payload</span>
      <fieldset className="sites-effect-toggle" aria-label="Payload source">
        <button
          type="button"
          className={
            source === "text" ? "sites-effect is-on is-allow" : "sites-effect"
          }
          onClick={() => setSource("text")}
        >
          Text
        </button>
        <button
          type="button"
          className={
            source === "file" ? "sites-effect is-on is-allow" : "sites-effect"
          }
          onClick={() => setSource("file")}
        >
          File
        </button>
      </fieldset>
      {source === "text" ? (
        <textarea
          id="drop-text"
          aria-label="Text to drop"
          rows={5}
          value={text}
          onChange={(event) => setText(event.target.value)}
        />
      ) : (
        <input
          id="drop-file"
          aria-label="File to drop"
          type="file"
          onChange={(event) => setFile(event.target.files?.[0] ?? null)}
        />
      )}
      <p className="hint">Up to 1 MiB once encrypted.</p>
    </div>
  );
}

/** The +new → Drop flow: a burner share whose payload never has to be vaulted. */
export function NewDropCeremony({
  initialName = "",
  initialFolder,
  onTypeChange,
}: {
  initialName?: string;
  initialFolder?: Folder;
  onTypeChange?: (typeId: string, name: string, folder: Folder | null) => void;
} = {}) {
  const {
    suggested,
    name,
    setName,
    folderId,
    setFolderId,
    source,
    setSource,
    text,
    setText,
    setFile,
    ttlMs,
    setTtlMs,
    keepCopy,
    setKeepCopy,
    busy,
    error,
    drop,
    path,
    submit,
  } = useNewDrop(initialName, initialFolder);

  if (drop) return <CreatedDropView drop={drop} />;
  return (
    <div className="detail">
      <form
        className="editor"
        onSubmit={(event) => {
          event.preventDefault();
          void submit();
        }}
      >
        <EditorTitle
          value={{ name, folderId }}
          folders={path.choices}
          onName={setName}
          onFolder={setFolderId}
          onBlur={path.blur}
          typeId="drop"
          placeholder={
            source === "file" ? "Defaults to the file name" : suggested
          }
          onTypeChange={
            onTypeChange &&
            ((typeId) => {
              const next = path.blur();
              if (next) onTypeChange(typeId, next.name, next.folder ?? null);
            })
          }
        />
        <DropPayloadFields
          source={source}
          setSource={setSource}
          text={text}
          setText={setText}
          setFile={setFile}
        />

        <TtlPicker value={ttlMs} onChange={setTtlMs} />

        <div className="field">
          <label className="check">
            <input
              type="checkbox"
              checked={keepCopy}
              onChange={(event) => setKeepCopy(event.target.checked)}
            />
            <span>Keep a copy on the drop record</span>
          </label>
        </div>

        {error ? (
          <p className="note note--err" role="alert">
            <span>{error}</span>
          </p>
        ) : null}
        <EditorActions
          busy={busy}
          label={busy ? "Sealing…" : "Seal and create drop"}
          closeTo="/vault"
        />
      </form>
    </div>
  );
}
