[package]
name = "opensesame-provider-openbao"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "OpenBao adapter"

[dependencies]
opensesame-domain = { path = "../domain" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
