[package]
name = "opensesame-provider-step-ca"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "step-ca adapter"

[dependencies]
opensesame-domain = { path = "../domain" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
