/**
 * Pure helpers behind scripts/quality/docs-index.mjs: read a title and a status out
 * of a Markdown document, and splice a generated table under a marker.
 */

export const MARKER =
  "<!-- generated by scripts/quality/docs-index.mjs; do not edit below -->";

/** First `# ` heading, without an `ADR 0001:` / `ADR 0001 —` prefix. */
export function title(text) {
  const heading = /^# +(.+)$/mu.exec(text)?.[1]?.trim() ?? "";
  return heading
    .replace(/^ADR[ -]?\d{4}\s*[:—–-]\s*/u, "")
    .replace(/\s+—\s+\d{4}-\d{2}-\d{2}$/u, "")
    .replace(/\|/gu, "\\|");
}

/**
 * The decision's status in a word or two. ADRs spell it three ways:
 * `## Status` followed by a line, `Status: X`, and `- **Status:** X`.
 */
export function status(text) {
  const section = /^## +Status\s*\n+([^\n]+)/mu.exec(text)?.[1];
  const inline = /^[-*\s]*\**Status:?\**:?\s*(.+)$/imu.exec(text)?.[1];
  const raw = (section ?? inline ?? "").replace(/\*/gu, "").trim();
  const word =
    /^(accepted|proposed|superseded|deprecated|rejected|draft)/iu.exec(
      raw,
    )?.[1];
  if (word === undefined) return raw === "" ? "—" : "See ADR";
  const normalized = word[0].toUpperCase() + word.slice(1).toLowerCase();
  return /supersed/iu.test(raw) && normalized !== "Superseded"
    ? `${normalized} (partly superseded)`
    : normalized;
}

export function adrRow(name, text) {
  const number = name.slice(0, 4);
  return [`[${number}](${name})`, title(text), status(text)];
}

export function auditRow(name, text) {
  return [name.slice(0, 10), `[${title(text)}](${name})`];
}

/** An evidence directory, linked to the README that lays it out. */
export function evidenceRow(name, text) {
  return [`[\`${name}/\`](${name}/README.md)`, title(text)];
}

/** Dated directories newest first, then the undated programme directories. */
export function evidenceOrder(a, b) {
  const dated = (name) => /^\d{4}-/u.test(name);
  if (dated(a) !== dated(b)) return dated(a) ? -1 : 1;
  return dated(a) ? b.localeCompare(a) : a.localeCompare(b);
}

/** Replace everything after the marker with a Markdown table. */
export function renderIndex(current, header, rows) {
  const at = current.indexOf(MARKER);
  const kept = at === -1 ? current : current.slice(0, at);
  const preamble = `${kept.trimEnd()}\n\n`;
  const lines = [
    `| ${header.join(" | ")} |`,
    `|${header.map(() => "---").join("|")}|`,
    ...rows.map((row) => `| ${row.join(" | ")} |`),
  ];
  return `${preamble}${MARKER}\n\n${lines.join("\n")}\n`;
}
