[package]
name = "opensesame-connection-broker"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "opensesame_connection_broker"
path = "src/lib.rs"

[dependencies]
opensesame-claims = { path = "../claims" }
opensesame-connection-detect = { path = "../connection-detect" }
opensesame-domain = { path = "../domain" }
opensesame-relay = { path = "../relay" }
opensesame-rotation = { path = "../rotation" }
opensesame-invoke-through = { path = "../invoke-through" }
secrecy = { workspace = true }
opensesame-task-bus = { path = "../task-bus" }
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
chacha20poly1305 = { workspace = true }
chrono = { workspace = true }
jsonwebtoken = { workspace = true }
oauth2 = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hmac = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
opensesame-storage = { path = "../storage" }
