/** Documented public-client alternatives to confidential integration OAuth. */
import type { NativeBrowserOAuthProfile } from "./native-browser-oauth-types.js";
export const APPROVED_BROWSER_OAUTH_PROFILES: readonly NativeBrowserOAuthProfile[] =
  [
    {
      id: "discord",
      mode: "implicit",
      name: "Discord",
      docsUrl:
        "https://docs.discord.com/developers/topics/oauth2#implicit-grant",
      refresh: false,
      revoke: "settings",
      revocationEndpoint: null,
      settingsUrl: "https://discord.com/channels/@me",
      publicParameters: ["authorization_outcome"],
      requiredScopes: ["identify"],
    },
    {
      id: "twitch",
      mode: "device-code",
      name: "Twitch",
      docsUrl:
        "https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#device-code-grant-flow",
      refresh: true,
      revoke: "form",
      revocationEndpoint: "https://id.twitch.tv/oauth2/revoke",
      settingsUrl: "https://www.twitch.tv/settings/connections",
      publicParameters: ["authorization_outcome"],
      requiredScopes: [],
    },
    {
      id: "vercel",
      mode: "pkce",
      name: "Vercel",
      docsUrl:
        "https://vercel.com/docs/sign-in-with-vercel/manage-from-dashboard",
      refresh: true,
      revoke: "form",
      revocationEndpoint: "https://api.vercel.com/login/oauth/token/revoke",
      settingsUrl: "https://vercel.com/account",
      publicParameters: [],
      requiredScopes: ["openid"],
    },
    {
      id: "codeberg",
      mode: "pkce",
      name: "Codeberg",
      docsUrl: "https://forgejo.org/docs/latest/user/oauth2-provider/",
      refresh: true,
      revoke: "settings",
      revocationEndpoint: null,
      settingsUrl: "https://codeberg.org/user/settings/applications",
      publicParameters: [],
      requiredScopes: [],
    },
    {
      id: "auth0",
      mode: "pkce",
      name: "Auth0",
      docsUrl:
        "https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-pkce",
      refresh: true,
      revoke: "form",
      revocationEndpoint: null,
      settingsUrl: "https://manage.auth0.com/",
      publicParameters: ["domain"],
      requiredScopes: ["openid", "email"],
    },
    {
      id: "okta",
      mode: "pkce",
      name: "Okta",
      docsUrl:
        "https://developer.okta.com/docs/guides/implement-grant-type/authcodepkce/main/",
      refresh: true,
      revoke: "form",
      revocationEndpoint: null,
      settingsUrl: null,
      publicParameters: ["domain"],
      requiredScopes: ["openid", "okta.users.read.self"],
    },
    {
      id: "crowdin",
      mode: "pkce",
      name: "Crowdin",
      docsUrl: "https://support.crowdin.com/developer/authorizing-oauth-apps/",
      refresh: true,
      revoke: "settings",
      revocationEndpoint: null,
      settingsUrl: "https://crowdin.com/settings",
      publicParameters: [],
      requiredScopes: ["user"],
    },
    {
      id: "databricks",
      mode: "pkce",
      name: "Databricks",
      docsUrl:
        "https://docs.databricks.com/aws/en/integrations/enable-disable-oauth",
      refresh: true,
      revoke: "settings",
      revocationEndpoint: null,
      settingsUrl: null,
      publicParameters: ["domain", "integration_id", "authorization_outcome"],
      requiredScopes: ["all-apis"],
    },
  ];
