#!/usr/bin/env python3
"""Reference for where a pepper goes in a produced password (ADR 0174).

Written against Python's own slicing, so the TypeScript and Rust readers are
checked against the language their expressions are borrowed from, not against
each other. It writes spec/conformance/pepper-position-vectors.json; with
`--check` it only compares the file on disk with what it would write.

The grammar, after one pass that drops ASCII whitespace:
  ``end`` (any ASCII case), or nothing        -> after the last character
  one optional ``[`` ... ``]`` around either form below
  ``i``                                        -> insert before index i
  ``a:b`` with either bound left out          -> stand in for s[a:b]
Anything else is not a position and means the end.

A password is cut into (head, tail); the vectors record how many characters
(code points, as Python counts them) each keeps for every length 0..MAX.
"""

import json
import pathlib
import re
import sys

MAX = 8
BOUNDS = range(-11, 12)
ASCII_WS = " \t\n\v\f\r"
INTEGER = re.compile(r"[+-]?[0-9]+")


def parse(expression):
    text = "".join(c for c in expression if c not in ASCII_WS)
    if len(text) >= 2 and text[0] == "[" and text[-1] == "]":
        text = text[1:-1]
    if text == "" or text.lower() == "end" and text.isascii():
        return ("end",)
    if ":" not in text:
        return ("insert", int(text)) if INTEGER.fullmatch(text) else ("end",)
    parts = text.split(":")
    if len(parts) != 2:
        return ("end",)
    bounds = []
    for part in parts:
        if part == "":
            bounds.append(None)
        elif INTEGER.fullmatch(part):
            bounds.append(int(part))
        else:
            return ("end",)
    return ("replace", bounds[0], bounds[1])


def cut(length, expression):
    """(head length, tail length) of a password of `length` characters."""
    s = "".join(chr(0x61 + i) for i in range(length))
    kind, *args = parse(expression)
    if kind == "end":
        head, tail = s, ""
    elif kind == "insert":
        head, tail = s[: args[0]], s[args[0] :]
    else:
        start, stop, _ = slice(args[0], args[1]).indices(length)
        head, tail = s[:start], s[max(start, stop) :]
    return [len(head), len(tail)]


def expressions():
    out = ["", "end", "END", "End", "eNd", " end ", "[end]", "[]", "[ ]", ":", "[:]"]
    out += [str(i) for i in BOUNDS]
    out += ["+" + str(i) for i in range(0, 12)] + ["00", "03", "-03", "+0", "-0"]
    out += ["[" + str(i) + "]" for i in BOUNDS] + [" 3 ", "\t-2\n", "[ 3 ]", " [ -2 ] "]
    big = "9" * 30
    out += [big, "-" + big, "+" + big, big + ":", ":" + big, "-" + big + ":", ":-" + big]
    out += [big + ":" + big, "-" + big + ":" + big, "-" + big + ":-" + big]
    out += ["0" * 40 + "3", "-" + "0" * 40 + "3"]
    bounds = [""] + [str(i) for i in BOUNDS]
    out += [a + ":" + b for a in bounds for b in bounds]
    out += ["[" + a + ":" + b + "]" for a in bounds[:: 2] for b in bounds[1:: 2]]
    out += ["2 : 5", "[ 2 : 5 ]", "+2:+5", "-3:", ":-3", "02:05"]
    # Not positions: every one means the end.
    out += [
        "abc", "e", "en", "ends", "ende", "1:2:3", "::", "1::2", ":::", "3.5", "--3",
        "+-3", "-+3", "0x3", "1_0", "1e1", "3a", "a3", "-", "+", "+:", ":+", "-:-",
        "[3", "3]", "[[3]]", "[[3]", "[3]]", "[:", ":]", "]3[", "[end", "end]",
        "end:", ":end", "end:3", "3:end", "1:b", "a:1", "1:2x",
        " 3", "3 ", "﻿3", "\u00853", " 3", "　3", "​3",
        "٣", "3٣", "٣:5", "1:٥", "３", "²",
        "ѕnd", "énd", "Kend", "İnd", "ſ",
        "\x003", "3\x00",
    ]
    seen, uniq = set(), []
    for e in out:
        if e not in seen:
            seen.add(e)
            uniq.append(e)
    return uniq


def build():
    return {
        "about": (
            "Where a pepper goes in a produced password (ADR 0174), checked "
            "against Python's own slicing. For each expression, `cuts[n]` is "
            "[head, tail]: how many characters (code points) of an n-character "
            "password come before and after the pepper. Generated by "
            "scripts/test/pepper-position-reference.py from Python's slice "
            "semantics, independent of the TypeScript and Rust readers; read by "
            "packages/vault-core and crates/sealed-store. Never regenerate to "
            "make a test pass."
        ),
        "maxLength": MAX,
        "cases": [
            {"expression": e, "cuts": [cut(n, e) for n in range(MAX + 1)]}
            for e in expressions()
        ],
    }


def main():
    path = pathlib.Path(__file__).resolve().parents[2] / "spec/conformance/pepper-position-vectors.json"
    built = build()
    cases = ",\n".join(
        "  " + json.dumps(case, ensure_ascii=True, separators=(", ", ": "))
        for case in built["cases"]
    )
    head = json.dumps({k: v for k, v in built.items() if k != "cases"}, ensure_ascii=True)
    text = head[:-1] + ',\n "cases": [\n' + cases + "\n ]\n}\n"
    if "--check" in sys.argv:
        if not path.exists() or path.read_text() != text:
            sys.exit(f"{path} is not what the reference writes")
        return
    path.write_text(text)
    print(f"{len(build()['cases'])} expressions -> {path}")


if __name__ == "__main__":
    main()
